--liquibase formatted sql
--changeset alp:V1.0.0.0.7__alter_questionnaire_response_views
CREATE OR REPLACE VIEW "VIEW::GDM.QUESTIONNAIRE_RESPONSE_BASE" AS
SELECT 
"QR"."ID", 
"QR"."PERSON_ID", 
"QR"."LANGUAGE", 
"QR"."QUESTIONNAIRE_REFERENCE", 
"QR"."QUESTIONNAIRE_VERSION", 
"QR"."STATUS", 
"QR"."AUTHORED",
"I"."ID" AS "ITEM_ID",
"I"."LINK_ID",
"I"."TEXT",
"I"."DEFINITION",
"ANS"."ID" AS "ANSWER_ID",
"ANS"."VALUE_TYPE",
"ANS"."VALUE",
"ANS"."VALUEATTACHMENT_CONTENTTYPE",
"ANS"."VALUEATTACHMENT_LANGUAGE",
"ANS"."VALUEATTACHMENT_DATA",
"ANS"."VALUEATTACHMENT_URL",
"ANS"."VALUEATTACHMENT_SIZE",
"ANS"."VALUEATTACHMENT_HASH",
"ANS"."VALUEATTACHMENT_TITLE",
"ANS"."VALUEATTACHMENT_CREATION",
"ANS"."VALUECODING_SYSTEM",
"ANS"."VALUECODING_VERSION",
"ANS"."VALUECODING_CODE",
"ANS"."VALUECODING_DISPLAY",
"ANS"."VALUECODING_USERSELECTED",
"ANS"."VALUEQUANTITY_VALUE",
"ANS"."VALUEQUANTITY_COMPARATOR",
"ANS"."VALUEQUANTITY_UNIT",
"ANS"."VALUEQUANTITY_SYSTEM",
"ANS"."VALUEQUANTITY_CODE",
"ANS"."VALUEREFERENCE_REFERENCE",
"ANS"."VALUEREFERENCE_TYPE",
"ANS"."VALUEREFERENCE_IDENTIFIER",
"ANS"."VALUEREFERENCE_DISPLAY"
FROM "GDM.QUESTIONNAIRE_RESPONSE" AS "QR" 
LEFT JOIN "GDM.ITEM" AS "I" 
ON "QR"."ID" = "I"."GDM_QUESTIONNAIRE_RESPONSE_ID"
LEFT JOIN "GDM.ANSWER" AS "ANS" 
ON "I"."ID" = "ANS"."GDM_ITEM_ID"
WITH READ ONLY;

--rollback DROP VIEW "VIEW::GDM.QUESTIONNAIRE_RESPONSE_BASE;
