--liquibase formatted sql
--changeset alp:V1.0.0.0.0__create_questionnaire_response_views
CREATE VIEW "VIEW::GDM.QUESTIONNAIRE_RESPONSE_BASE" AS
SELECT 
"QR"."ID", 
"QR"."ALP_ID", 
"QR"."LANGUAGE", 
"QR"."QUESTIONNAIRE_REFERENCE", 
"QR"."QUESTIONNAIRE_VERSION", 
"QR"."STATUS", 
"QR"."AUTHORED",
"I"."LINK_ID",
"I"."TEXT",
"I"."DEFINITION",
"ANS"."VALUE_TYPE",
"ANS"."VALUE",
"ANS"."VALUEATTACHMENT_CONTENTTYPE",
"ANS"."VALUEATTACHMENT_LANGUAGE",
"ANS"."VALUEATTACHMENT_DATA",
"ANS"."VALUEATTACHMENT_URL",
"ANS"."VALUEATTACHMENT_SIZE",
"ANS"."VALUEATTACHMENT_HASH",
"ANS"."VALUEATTACHMENT_TITLE",
"ANS"."VALUEATTACHMENT_CREATION",
"ANS"."VALUECODING_SYSTEM",
"ANS"."VALUECODING_VERSION",
"ANS"."VALUECODING_CODE",
"ANS"."VALUECODING_DISPLAY",
"ANS"."VALUECODING_USERSELECTED",
"ANS"."VALUEQUANTITY_VALUE",
"ANS"."VALUEQUANTITY_COMPARATOR",
"ANS"."VALUEQUANTITY_UNIT",
"ANS"."VALUEQUANTITY_SYSTEM",
"ANS"."VALUEQUANTITY_CODE",
"ANS"."VALUEREFERENCE_REFERENCE",
"ANS"."VALUEREFERENCE_TYPE",
"ANS"."VALUEREFERENCE_IDENTIFIER",
"ANS"."VALUEREFERENCE_DISPLAY"
FROM "GDM.QUESTIONNAIRE_RESPONSE" AS "QR" 
INNER JOIN "GDM.ITEM" AS "I" 
ON "QR"."ID" = "I"."GDM_QUESTIONNAIRE_RESPONSE_ID"
INNER JOIN "GDM.ANSWER" AS "ANS" 
ON "I"."ID" = "ANS"."GDM_ITEM_ID"
WITH READ ONLY;



CREATE VIEW "VIEW::GDM.QUESTIONNAIRE_RESPONSE_LATEST" AS
SELECT "B".*
FROM (
	SELECT "ALP_ID", "QUESTIONNAIRE_REFERENCE", "LINK_ID", MAX("AUTHORED") AS "MAX_AUTHORED"
	FROM "VIEW::GDM.QUESTIONNAIRE_RESPONSE_BASE" 
	GROUP BY "ALP_ID", "QUESTIONNAIRE_REFERENCE", "LINK_ID"
) AS "TEMP" 
INNER JOIN "VIEW::GDM.QUESTIONNAIRE_RESPONSE_BASE" AS "B" 
ON "TEMP"."ALP_ID" = "B"."ALP_ID"
AND "TEMP"."QUESTIONNAIRE_REFERENCE" = "B"."QUESTIONNAIRE_REFERENCE"
AND "TEMP"."LINK_ID" = "B"."LINK_ID"
AND "TEMP"."MAX_AUTHORED" = "B"."AUTHORED"
WITH READ ONLY;

--rollback DROP VIEW "VIEW::GDM.QUESTIONNAIRE_RESPONSE_LATEST";
--rollback DROP VIEW "VIEW::GDM.QUESTIONNAIRE_RESPONSE_BASE;