--liquibase formatted sql
--changeset alp:V1.0.0.0.2__alter_questionnaire_response_table
ALTER TABLE "GDM.QUESTIONNAIRE_RESPONSE" 
DROP(RECORD_ID);

ALTER TABLE "GDM.QUESTIONNAIRE_RESPONSE" 
ALTER ("ID" VARCHAR(1000));

ALTER TABLE "GDM.QUESTIONNAIRE_RESPONSE"
ADD(ETL_UPDATED_AT SECONDDATE NULL);

--rollback ALTER TABLE "GDM.QUESTIONNAIRE_RESPONSE" DROP(ETL_UPDATED_AT);
--rollback ALTER TABLE "GDM.QUESTIONNAIRE_RESPONSE" ALTER ("ID" VARCHAR(50));
--rollback ALTER TABLE "GDM.QUESTIONNAIRE_RESPONSE" ADD(RECORD_ID VARCHAR(1000) NULL);