--liquibase formatted sql
--changeset alp:V1.0.0.0.5__alter_questionnaire_response_table

ALTER TABLE "GDM.QUESTIONNAIRE_RESPONSE" 
DROP(ALP_ID);

ALTER TABLE "GDM.QUESTIONNAIRE_RESPONSE"
ADD(PERSON_ID BIGINT NOT NULL);

--rollback ALTER TABLE "GDM.QUESTIONNAIRE_RESPONSE" DROP(PERSON_ID);
--rollback ALTER TABLE "GDM.QUESTIONNAIRE_RESPONSE" ADD("ALP_ID" VARCHAR(50));