--liquibase formatted sql
--changeset alp:V1.0.0.0.8__alter_research_subject_table
ALTER TABLE "GDM.RESEARCH_SUBJECT"
ADD(SOURCE_INDIVIDUAL_IDENTIFIER_VALUE VARCHAR(500) NULL);

--rollback ALTER TABLE "GDM.RESEARCH_SUBJECT" DROP(SOURCE_INDIVIDUAL_IDENTIFIER_VALUE);