--liquibase formatted sql
--changeset alp:V5.4.1.2.4__add_cols_to_views

CREATE OR REPLACE VIEW "VIEW::OMOP.COND" (
    "CONDITION_OCCURRENCE_ID",
    "CONDITION_CONCEPT_ID",
    "CONDITION_NAME",
    "CONDITION_TYPE_NAME",
    "CONDITION_SOURCE_NAME",
    "CONDITION_STATUS_NAME",
    "PATIENT_ID",
    "CONDITION_START_DATE",
    "CONDITION_END_DATE",
    "VISIT_OCCURRENCE_ID",
    "CONDITION_SOURCE_VALUE",
    "CONDITION_CONCEPT_CODE",
    "CONDITION_TYPE_CONCEPT_ID",
    "CONDITION_TYPE_CONCEPT_CODE",
    "CONDITION_SOURCE_CONCEPT_ID",
    "CONDITION_SOURCE_CONCEPT_CODE",
    "CONDITION_STATUS_CONCEPT_ID",
    "CONDITION_STATUS_CONCEPT_CODE"
  ) AS
SELECT
  "co_$0"."CONDITION_OCCURRENCE_ID",
  "co_$0"."CONDITION_CONCEPT_ID",
  "c_$2"."CONCEPT_NAME" AS "CONDITION_NAME",
  "t_$3"."CONCEPT_NAME" AS "CONDITION_TYPE_NAME",
  "s_$4"."CONCEPT_NAME" AS "CONDITION_SOURCE_NAME",
  "cs_$5"."CONCEPT_NAME" AS "CONDITION_STATUS_NAME",
  "p_$1"."PATIENT_ID",
  "co_$0"."CONDITION_START_DATE",
  "co_$0"."CONDITION_END_DATE",
  "co_$0"."VISIT_OCCURRENCE_ID",
  "co_$0"."CONDITION_SOURCE_VALUE",
  "c_$2"."CONCEPT_CODE" AS "CONDITION_CONCEPT_CODE",
  "co_$0"."CONDITION_TYPE_CONCEPT_ID" AS "CONDITION_TYPE_CONCEPT_ID",
  "t_$3"."CONCEPT_CODE" AS "CONDITION_TYPE_CONCEPT_CODE",
  "co_$0"."CONDITION_SOURCE_CONCEPT_ID" AS "CONDITION_SOURCE_CONCEPT_ID",
  "s_$4"."CONCEPT_CODE" AS "CONDITION_SOURCE_CONCEPT_CODE",
  "co_$0"."CONDITION_STATUS_CONCEPT_ID" AS "CONDITION_STATUS_CONCEPT_ID",
  "cs_$5"."CONCEPT_CODE" AS "CONDITION_STATUS_CONCEPT_CODE"
FROM
  (
    (
      (
        (
          (
            "CONDITION_OCCURRENCE" AS "co_$0"
            INNER JOIN "VIEW::OMOP.PATIENT" AS "p_$1" ON ("co_$0"."PERSON_ID" = "p_$1"."PATIENT_ID")
          )
          LEFT JOIN "VIEW::OMOP.CONCEPT" AS "c_$2" ON (
            "c_$2"."CONCEPT_ID" = "co_$0"."CONDITION_CONCEPT_ID"
          )
        )
        LEFT JOIN "VIEW::OMOP.CONCEPT" AS "t_$3" ON (
          "t_$3"."CONCEPT_ID" = "co_$0"."CONDITION_TYPE_CONCEPT_ID"
        )
      )
      LEFT OUTER JOIN "VIEW::OMOP.CONCEPT" AS "s_$4" ON (
        "s_$4"."CONCEPT_ID" = "co_$0"."CONDITION_SOURCE_CONCEPT_ID"
      )
    )
    LEFT OUTER JOIN "VIEW::OMOP.CONCEPT" AS "cs_$5" ON (
      "cs_$5"."CONCEPT_ID" = "co_$0"."CONDITION_STATUS_CONCEPT_ID"
    )
  ) 
WITH READ ONLY;



CREATE OR REPLACE VIEW "VIEW::OMOP.DEATH" (
    "PATIENT_ID",
    "DEATH_TYPE_NAME",
    "DEATH_DATE",
    "DEATH_DATETIME",
    "DEATH_TYPE_CONCEPT_ID",
    "DEATH_TYPE_CONCEPT_CODE"
  ) AS
SELECT
  "p_$1"."PATIENT_ID",
  "c_$2"."CONCEPT_NAME" AS "DEATH_TYPE_NAME",
  "d_$0"."DEATH_DATE",
  "d_$0"."DEATH_DATETIME",
  "d_$0"."DEATH_TYPE_CONCEPT_ID" AS "DEATH_TYPE_CONCEPT_ID",
  "c_$2"."CONCEPT_CODE" AS "DEATH_TYPE_CONCEPT_CODE"
FROM
  (
    (
      "DEATH" AS "d_$0"
      INNER JOIN "VIEW::OMOP.PATIENT" AS "p_$1" ON ("d_$0"."PERSON_ID" = "p_$1"."PATIENT_ID")
    )
    LEFT JOIN "VIEW::OMOP.CONCEPT" AS "c_$2" ON (
      "c_$2"."CONCEPT_ID" = "d_$0"."DEATH_TYPE_CONCEPT_ID"
    )
  ) 
WITH READ ONLY;


CREATE OR REPLACE VIEW "VIEW::OMOP.DEVICE_EXPOSURE" (
    "DEVICE_EXPOSURE_ID",
    "PATIENT_ID",
    "DEVICE_NAME",
    "DEVICE_CONCEPT_ID",
    "DEVICE_EXPOSURE_START_DATE",
    "DEVICE_EXPOSURE_END_DATE",
    "DEVICE_TYPE_NAME",
    "VISIT_OCCURRENCE_ID",
    "DEVICE_CONCEPT_CODE",
    "DEVICE_TYPE_CONCEPT_ID",
    "DEVICE_TYPE_CONCEPT_CODE"
  ) AS
SELECT
  "de_$0"."DEVICE_EXPOSURE_ID",
  "p_$1"."PATIENT_ID",
  "c_$2"."CONCEPT_NAME" AS "DEVICE_NAME",
  "de_$0"."DEVICE_CONCEPT_ID",
  "de_$0"."DEVICE_EXPOSURE_START_DATE",
  "de_$0"."DEVICE_EXPOSURE_END_DATE",
  "ct_$3"."CONCEPT_NAME" AS "DEVICE_TYPE_NAME",
  "de_$0"."VISIT_OCCURRENCE_ID",
  "c_$2"."CONCEPT_CODE" AS "DEVICE_CONCEPT_CODE",
  "de_$0"."DEVICE_TYPE_CONCEPT_ID" AS "DEVICE_TYPE_CONCEPT_ID",
  "ct_$3"."CONCEPT_CODE" AS "DEVICE_TYPE_CONCEPT_CODE"
FROM
  (
    (
      (
        "DEVICE_EXPOSURE" AS "de_$0"
        INNER JOIN "VIEW::OMOP.PATIENT" AS "p_$1" ON ("de_$0"."PERSON_ID" = "p_$1"."PATIENT_ID")
      )
      LEFT JOIN "VIEW::OMOP.CONCEPT" AS "c_$2" ON (
        "c_$2"."CONCEPT_ID" = "de_$0"."DEVICE_CONCEPT_ID"
      )
    )
    LEFT JOIN "VIEW::OMOP.CONCEPT" AS "ct_$3" ON (
      "ct_$3"."CONCEPT_ID" = "de_$0"."DEVICE_TYPE_CONCEPT_ID"
    )
  ) 
WITH READ ONLY;


CREATE OR REPLACE VIEW "VIEW::OMOP.DOSE_ERA" (
    "DOSE_ERA_ID",
    "PATIENT_ID",
    "DRUG_NAME",
    "UNIT_NAME",
    "DOSE_VALUE",
    "DOSE_ERA_START_DATE",
    "DOSE_ERA_END_DATE",
    "DRUG_CONCEPT_ID",
    "DRUG_CONCEPT_CODE",
    "UNIT_CONCEPT_ID",
    "UNIT_CONCEPT_CODE"
  ) AS
SELECT
  "de_$0"."DOSE_ERA_ID",
  "p_$1"."PATIENT_ID",
  "c_$2"."CONCEPT_NAME" AS "DRUG_NAME",
  "u_$3"."CONCEPT_NAME" AS "UNIT_NAME",
  "de_$0"."DOSE_VALUE",
  "de_$0"."DOSE_ERA_START_DATE",
  "de_$0"."DOSE_ERA_END_DATE",
  "de_$0"."DRUG_CONCEPT_ID" AS "DRUG_CONCEPT_ID",
  "c_$2"."CONCEPT_CODE" AS "DRUG_CONCEPT_CODE",
  "de_$0"."UNIT_CONCEPT_ID" AS "UNIT_CONCEPT_ID",
  "u_$3"."CONCEPT_CODE" AS "UNIT_CONCEPT_CODE"
FROM
  (
    (
      (
        "DOSE_ERA" AS "de_$0"
        INNER JOIN "VIEW::OMOP.PATIENT" AS "p_$1" ON ("de_$0"."PERSON_ID" = "p_$1"."PATIENT_ID")
      )
      LEFT JOIN "VIEW::OMOP.CONCEPT" AS "c_$2" ON (
        "c_$2"."CONCEPT_ID" = "de_$0"."DRUG_CONCEPT_ID"
      )
    )
    LEFT JOIN "VIEW::OMOP.CONCEPT" AS "u_$3" ON (
      "u_$3"."CONCEPT_ID" = "de_$0"."UNIT_CONCEPT_ID"
    )
  ) 
WITH READ ONLY;


CREATE OR REPLACE VIEW "VIEW::OMOP.DRUG_ERA" (
    "DRUG_ERA_ID",
    "PATIENT_ID",
    "DRUG_NAME",
    "DRUG_ERA_START_DATE",
    "DRUG_ERA_END_DATE",
    "DRUG_EXPOSURE_COUNT",
    "GAP_DAYS",
    "DRUG_CONCEPT_ID",
    "DRUG_CONCEPT_CODE"
  ) AS
SELECT
  "de_$0"."DRUG_ERA_ID",
  "p_$1"."PATIENT_ID",
  "c_$2"."CONCEPT_NAME" AS "DRUG_NAME",
  "de_$0"."DRUG_ERA_START_DATE",
  "de_$0"."DRUG_ERA_END_DATE",
  "de_$0"."DRUG_EXPOSURE_COUNT",
  "de_$0"."GAP_DAYS",
  "de_$0"."DRUG_CONCEPT_ID" AS "DRUG_CONCEPT_ID",
  "c_$2"."CONCEPT_CODE" AS "DRUG_CONCEPT_CODE"
FROM
  (
    (
      "DRUG_ERA" AS "de_$0"
      INNER JOIN "VIEW::OMOP.PATIENT" AS "p_$1" ON ("de_$0"."PERSON_ID" = "p_$1"."PATIENT_ID")
    )
    LEFT OUTER JOIN "VIEW::OMOP.CONCEPT" AS "c_$2" ON (
      "c_$2"."CONCEPT_ID" = "de_$0"."DRUG_CONCEPT_ID"
    )
  ) 
WITH READ ONLY;


CREATE OR REPLACE VIEW "VIEW::OMOP.MEAS" (
    "MEASUREMENT_ID",
    "MEASUREMENT_CONCEPT_ID",
    "MEASUREMENT_NAME",
    "MEASUREMENT_TYPE_NAME",
    "MEASUREMENT_VALUE_NAME",
    "PATIENT_ID",
    "MEASUREMENT_DATE",
    "VALUE_AS_NUMBER",
    "VISIT_OCCURRENCE_ID",
    "MEASUREMENT_CONCEPT_CODE",
    "MEASUREMENT_TYPE_CONCEPT_ID",
    "MEASUREMENT_TYPE_CONCEPT_CODE",
    "VALUE_AS_CONCEPT_ID",
    "VALUE_AS_CONCEPT_CODE",
    "UNIT_CONCEPT_ID",
    "UNIT_CONCEPT_CODE"
  ) AS
SELECT
  "m_$0"."MEASUREMENT_ID",
  "m_$0"."MEASUREMENT_CONCEPT_ID",
  "c_$2"."CONCEPT_NAME" AS "MEASUREMENT_NAME",
  "t_$3"."CONCEPT_NAME" AS "MEASUREMENT_TYPE_NAME",
  "vt_$4"."CONCEPT_NAME" AS "MEASUREMENT_VALUE_NAME",
  "p_$1"."PATIENT_ID",
  "m_$0"."MEASUREMENT_DATE",
  "m_$0"."VALUE_AS_NUMBER",
  "m_$0"."VISIT_OCCURRENCE_ID",
  "c_$2"."CONCEPT_CODE" AS "MEASUREMENT_CONCEPT_CODE",
  "m_$0"."MEASUREMENT_TYPE_CONCEPT_ID" AS "MEASUREMENT_TYPE_CONCEPT_ID",
  "t_$3"."CONCEPT_CODE" AS "MEASUREMENT_TYPE_CONCEPT_CODE",
  "m_$0"."VALUE_AS_CONCEPT_ID" AS "VALUE_AS_CONCEPT_ID",
  "vt_$4"."CONCEPT_CODE" AS "VALUE_AS_CONCEPT_CODE",
  "m_$0"."UNIT_CONCEPT_ID" AS "UNIT_CONCEPT_ID",
  "u_$5"."CONCEPT_CODE" AS "UNIT_CONCEPT_CODE"
FROM
  (
    (
      (
        (
          (
            "MEASUREMENT" AS "m_$0"
            INNER JOIN "VIEW::OMOP.PATIENT" AS "p_$1" ON ("m_$0"."PERSON_ID" = "p_$1"."PATIENT_ID")
          )
          LEFT JOIN "VIEW::OMOP.CONCEPT" AS "c_$2" ON (
            "c_$2"."CONCEPT_ID" = "m_$0"."MEASUREMENT_CONCEPT_ID"
          )
        )
        LEFT OUTER JOIN "VIEW::OMOP.CONCEPT" AS "t_$3" ON (
          "t_$3"."CONCEPT_ID" = "m_$0"."MEASUREMENT_TYPE_CONCEPT_ID"
        )
      )
      LEFT OUTER JOIN "VIEW::OMOP.CONCEPT" AS "vt_$4" ON (
        "vt_$4"."CONCEPT_ID" = "m_$0"."VALUE_AS_CONCEPT_ID"
      )
    )
    LEFT OUTER JOIN "VIEW::OMOP.CONCEPT" AS "u_$5" ON ("u_$5"."CONCEPT_ID" = "m_$0"."UNIT_CONCEPT_ID")
  ) 
WITH READ ONLY;


CREATE OR REPLACE VIEW "VIEW::OMOP.VISIT" (
    "VISIT_OCCURRENCE_ID",
    "VISIT_CONCEPT_ID",
    "VISIT_NAME",
    "VISIT_TYPE_NAME",
    "PATIENT_ID",
    "VISIT_START_DATE",
    "PRECEDING_VISIT_OCCURRENCE_ID",
    "VISIT_END_DATE",
    "VISIT_CONCEPT_CODE",
    "VISIT_TYPE_CONCEPT_ID",
    "VISIT_TYPE_CONCEPT_CODE"
  ) AS
SELECT
  "vo_$0"."VISIT_OCCURRENCE_ID",
  "vo_$0"."VISIT_CONCEPT_ID",
  "c_$2"."CONCEPT_NAME" AS "VISIT_NAME",
  "t_$3"."CONCEPT_NAME" AS "VISIT_TYPE_NAME",
  "p_$1"."PATIENT_ID",
  "vo_$0"."VISIT_START_DATE",
  "vo_$0"."PRECEDING_VISIT_OCCURRENCE_ID",
  "vo_$0"."VISIT_END_DATE",
  "c_$2"."CONCEPT_CODE" AS "VISIT_CONCEPT_CODE",
  "vo_$0"."VISIT_TYPE_CONCEPT_ID" AS "VISIT_TYPE_CONCEPT_ID",
  "t_$3"."CONCEPT_CODE" AS "VISIT_TYPE_CONCEPT_CODE"
FROM
  (
    (
      (
        "VISIT_OCCURRENCE" AS "vo_$0"
        INNER JOIN "VIEW::OMOP.PATIENT" AS "p_$1" ON ("vo_$0"."PERSON_ID" = "p_$1"."PATIENT_ID")
      )
      LEFT JOIN "VIEW::OMOP.CONCEPT" AS "c_$2" ON (
        "c_$2"."CONCEPT_ID" = "vo_$0"."VISIT_CONCEPT_ID"
      )
    )
    LEFT JOIN "VIEW::OMOP.CONCEPT" AS "t_$3" ON (
      "t_$3"."CONCEPT_ID" = "vo_$0"."VISIT_TYPE_CONCEPT_ID"
    )
  ) 
WITH READ ONLY;