--liquibase formatted sql
--changeset alp:V5.4.1.1.8_alter_fuzzy_index_concept_table.sql

ALTER TABLE CONCEPT DROP SYSTEM VERSIONING;

ALTER TABLE CONCEPT ALTER (CONCEPT_CODE NVARCHAR(1000) FUZZY SEARCH INDEX ON, CONCEPT_CLASS_ID NVARCHAR(1000) FUZZY SEARCH INDEX ON, DOMAIN_ID NVARCHAR(20) FUZZY SEARCH INDEX ON, VOCABULARY_ID NVARCHAR(20) FUZZY SEARCH INDEX ON);

CREATE FULLTEXT INDEX index_on_domain_id ON CONCEPT(DOMAIN_ID);
CREATE FULLTEXT INDEX index_on_vocabulary_id ON CONCEPT(VOCABULARY_ID);

--HISTRORY TABLE
ALTER TABLE CONCEPT_HISTORY ALTER (CONCEPT_CODE NVARCHAR(1000) FUZZY SEARCH INDEX ON, CONCEPT_CLASS_ID NVARCHAR(1000) FUZZY SEARCH INDEX ON, DOMAIN_ID NVARCHAR(20) FUZZY SEARCH INDEX ON, VOCABULARY_ID NVARCHAR(20) FUZZY SEARCH INDEX ON);

CREATE FULLTEXT INDEX index_on_domain_id_history ON CONCEPT_HISTORY(DOMAIN_ID);
CREATE FULLTEXT INDEX index_on_vocabulary_id_history ON CONCEPT_HISTORY(VOCABULARY_ID);

ALTER TABLE "CONCEPT" ADD SYSTEM VERSIONING HISTORY TABLE "CONCEPT_HISTORY";
