--liquibase formatted sql
--changeset alp:V5.4.1.1.5__alter_omop_tables_add_versioning.sql

-- CONCEPT
CREATE COLUMN TABLE "CONCEPT_HISTORY" AS 
(
    SELECT * FROM "CONCEPT"
);

ALTER TABLE "CONCEPT" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);

ALTER TABLE "CONCEPT_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- RADIOLOGY_IMAGE
CREATE COLUMN TABLE "RADIOLOGY_IMAGE_HISTORY" AS 
(
    SELECT * FROM "RADIOLOGY_IMAGE"
);

ALTER TABLE "RADIOLOGY_IMAGE" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);

ALTER TABLE "RADIOLOGY_IMAGE_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- RADIOLOGY_OCCURRENCE
CREATE COLUMN TABLE "RADIOLOGY_OCCURRENCE_HISTORY" AS 
(
    SELECT * FROM "RADIOLOGY_OCCURRENCE"
);

ALTER TABLE "RADIOLOGY_OCCURRENCE" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);

ALTER TABLE "RADIOLOGY_OCCURRENCE_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- DOMAIN
CREATE COLUMN TABLE "DOMAIN_HISTORY" AS 
(
    SELECT * FROM "DOMAIN"
);

ALTER TABLE "DOMAIN" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);

ALTER TABLE "DOMAIN_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- CONCEPT_CLASS
CREATE COLUMN TABLE "CONCEPT_CLASS_HISTORY" AS 
(
    SELECT * FROM "CONCEPT_CLASS"
);

ALTER TABLE "CONCEPT_CLASS" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);

ALTER TABLE "CONCEPT_CLASS_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- CONCEPT_RELATIONSHIP
CREATE COLUMN TABLE "CONCEPT_RELATIONSHIP_HISTORY" AS 
(
    SELECT * FROM "CONCEPT_RELATIONSHIP"
);
ALTER TABLE "CONCEPT_RELATIONSHIP" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "CONCEPT_RELATIONSHIP_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- RELATIONSHIP
CREATE COLUMN TABLE "RELATIONSHIP_HISTORY" AS 
(
    SELECT * FROM "RELATIONSHIP"
);

ALTER TABLE "RELATIONSHIP" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "RELATIONSHIP_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- CONCEPT_SYNONYM
CREATE COLUMN TABLE "CONCEPT_SYNONYM_HISTORY" AS 
(
    SELECT * FROM "CONCEPT_SYNONYM"
);

ALTER TABLE "CONCEPT_SYNONYM" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "CONCEPT_SYNONYM_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- CONCEPT_ANCESTOR
CREATE COLUMN TABLE "CONCEPT_ANCESTOR_HISTORY" AS 
(
    SELECT * FROM "CONCEPT_ANCESTOR"
);

ALTER TABLE "CONCEPT_ANCESTOR" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);

ALTER TABLE "CONCEPT_ANCESTOR_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- SOURCE_TO_CONCEPT_MAP
CREATE COLUMN TABLE "SOURCE_TO_CONCEPT_MAP_HISTORY" AS 
(
    SELECT * FROM "SOURCE_TO_CONCEPT_MAP"
);

ALTER TABLE "SOURCE_TO_CONCEPT_MAP" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "SOURCE_TO_CONCEPT_MAP_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- DRUG_STRENGTH
CREATE COLUMN TABLE "DRUG_STRENGTH_HISTORY" AS 
(
    SELECT * FROM "DRUG_STRENGTH"
);

ALTER TABLE "DRUG_STRENGTH" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "DRUG_STRENGTH_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- COHORT_DEFINITION
CREATE COLUMN TABLE "COHORT_DEFINITION_HISTORY" AS 
(
    SELECT * FROM "COHORT_DEFINITION"
);

ALTER TABLE "COHORT_DEFINITION" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "COHORT_DEFINITION_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- ATTRIBUTE_DEFINITION
CREATE COLUMN TABLE "ATTRIBUTE_DEFINITION_HISTORY" AS 
(
    SELECT * FROM "ATTRIBUTE_DEFINITION"
);

ALTER TABLE "ATTRIBUTE_DEFINITION" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "ATTRIBUTE_DEFINITION_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- PERSON
CREATE COLUMN TABLE "PERSON_HISTORY" AS 
(
    SELECT * FROM "PERSON"
);

ALTER TABLE "PERSON" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);

ALTER TABLE "PERSON_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- OBSERVATION_PERIOD
CREATE COLUMN TABLE "OBSERVATION_PERIOD_HISTORY" AS 
(
    SELECT * FROM "OBSERVATION_PERIOD"
);

ALTER TABLE "OBSERVATION_PERIOD" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "OBSERVATION_PERIOD_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- SPECIMEN
CREATE COLUMN TABLE "SPECIMEN_HISTORY" AS 
(
    SELECT * FROM "SPECIMEN"
);

ALTER TABLE "SPECIMEN" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "SPECIMEN_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- DEATH
CREATE COLUMN TABLE "DEATH_HISTORY" AS 
(
    SELECT * FROM "DEATH"
);
ALTER TABLE "DEATH" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "DEATH_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- VISIT_OCCURRENCE
CREATE COLUMN TABLE "VISIT_OCCURRENCE_HISTORY" AS 
(
    SELECT * FROM "VISIT_OCCURRENCE"
);

ALTER TABLE "VISIT_OCCURRENCE" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "VISIT_OCCURRENCE_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- PROCEDURE_OCCURRENCE
CREATE COLUMN TABLE "PROCEDURE_OCCURRENCE_HISTORY" AS 
(
    SELECT * FROM "PROCEDURE_OCCURRENCE"
);
ALTER TABLE "PROCEDURE_OCCURRENCE" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "PROCEDURE_OCCURRENCE_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- DRUG_EXPOSURE
CREATE COLUMN TABLE "DRUG_EXPOSURE_HISTORY" AS 
(
    SELECT * FROM "DRUG_EXPOSURE"
);

ALTER TABLE "DRUG_EXPOSURE" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "DRUG_EXPOSURE_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- DEVICE_EXPOSURE
CREATE COLUMN TABLE "DEVICE_EXPOSURE_HISTORY" AS 
(
    SELECT * FROM "DEVICE_EXPOSURE"
);

ALTER TABLE "DEVICE_EXPOSURE" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "DEVICE_EXPOSURE_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- CONDITION_OCCURRENCE
CREATE COLUMN TABLE "CONDITION_OCCURRENCE_HISTORY" AS 
(
    SELECT * FROM "CONDITION_OCCURRENCE"
);

ALTER TABLE "CONDITION_OCCURRENCE" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "CONDITION_OCCURRENCE_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- MEASUREMENT
CREATE COLUMN TABLE "MEASUREMENT_HISTORY" AS 
(
    SELECT * FROM "MEASUREMENT"
);

ALTER TABLE "MEASUREMENT" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "MEASUREMENT_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- NOTE
CREATE COLUMN TABLE "NOTE_HISTORY" AS 
(
    SELECT * FROM "NOTE"
);

ALTER TABLE "NOTE" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);

ALTER TABLE "NOTE_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- NOTE_NLP
CREATE COLUMN TABLE "NOTE_NLP_HISTORY" AS 
(
    SELECT * FROM "NOTE_NLP"
);

ALTER TABLE "NOTE_NLP" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "NOTE_NLP_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- OBSERVATION
CREATE COLUMN TABLE "OBSERVATION_HISTORY" AS 
(
    SELECT * FROM "OBSERVATION"
);

ALTER TABLE "OBSERVATION" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "OBSERVATION_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- FACT_RELATIONSHIP
CREATE COLUMN TABLE "FACT_RELATIONSHIP_HISTORY" AS 
(
    SELECT * FROM "FACT_RELATIONSHIP"
);

ALTER TABLE "FACT_RELATIONSHIP" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);

ALTER TABLE "FACT_RELATIONSHIP_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- Location
CREATE COLUMN TABLE "LOCATION_HISTORY" AS 
(
    SELECT * FROM "LOCATION"
);

ALTER TABLE "LOCATION" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);

ALTER TABLE "LOCATION_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- CARE_SITE
CREATE COLUMN TABLE "CARE_SITE_HISTORY" AS 
(
    SELECT * FROM "CARE_SITE"
);

ALTER TABLE "CARE_SITE" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);

ALTER TABLE "CARE_SITE_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- PROVIDER
CREATE COLUMN TABLE "PROVIDER_HISTORY" AS 
(
    SELECT * FROM "PROVIDER"
);

ALTER TABLE "PROVIDER" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "PROVIDER_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- PAYER_PLAN_PERIOD
CREATE COLUMN TABLE "PAYER_PLAN_PERIOD_HISTORY" AS 
(
    SELECT * FROM "PAYER_PLAN_PERIOD"
);

ALTER TABLE "PAYER_PLAN_PERIOD" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "PAYER_PLAN_PERIOD_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- COST
CREATE COLUMN TABLE "COST_HISTORY" AS 
(
    SELECT * FROM "COST"
);

ALTER TABLE "COST" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);

ALTER TABLE "COST_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- COHORT
CREATE COLUMN TABLE "COHORT_HISTORY" AS 
(
    SELECT * FROM "COHORT"
);

ALTER TABLE "COHORT" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);

ALTER TABLE "COHORT_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- COHORT_ATTRIBUTE
CREATE COLUMN TABLE "COHORT_ATTRIBUTE_HISTORY" AS 
(
    SELECT * FROM "COHORT_ATTRIBUTE"
);

ALTER TABLE "COHORT_ATTRIBUTE" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);

ALTER TABLE "COHORT_ATTRIBUTE_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- DRUG_ERA
CREATE COLUMN TABLE "DRUG_ERA_HISTORY" AS 
(
    SELECT * FROM "DRUG_ERA"
);

ALTER TABLE "DRUG_ERA" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);

ALTER TABLE "DRUG_ERA_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- DOSE_ERA
CREATE COLUMN TABLE "DOSE_ERA_HISTORY" AS 
(
    SELECT * FROM "DOSE_ERA"
);

ALTER TABLE "DOSE_ERA" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);

ALTER TABLE "DOSE_ERA_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- CONDITION_ERA
CREATE COLUMN TABLE "CONDITION_ERA_HISTORY" AS 
(
    SELECT * FROM "CONDITION_ERA"
);

ALTER TABLE "CONDITION_ERA" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);

ALTER TABLE "CONDITION_ERA_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- VISIT_DETAIL
CREATE COLUMN TABLE "VISIT_DETAIL_HISTORY" AS 
(
    SELECT * FROM "VISIT_DETAIL"
);

ALTER TABLE "VISIT_DETAIL" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);

ALTER TABLE "VISIT_DETAIL_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- METADATA
CREATE COLUMN TABLE "METADATA_HISTORY" AS 
(
    SELECT * FROM "METADATA"
);

ALTER TABLE "METADATA" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);

ALTER TABLE "METADATA_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- SURVEY_CONDUCT
CREATE COLUMN TABLE "SURVEY_CONDUCT_HISTORY" AS 
(
    SELECT * FROM "SURVEY_CONDUCT"
);

ALTER TABLE "SURVEY_CONDUCT" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);

ALTER TABLE "SURVEY_CONDUCT_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- CONCEPT_HIERARCHY
CREATE COLUMN TABLE "CONCEPT_HIERARCHY_HISTORY" AS 
(
    SELECT * FROM "CONCEPT_HIERARCHY"
);

ALTER TABLE "CONCEPT_HIERARCHY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);

ALTER TABLE "CONCEPT_HIERARCHY_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

	ALTER TABLE "CONCEPT" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "RADIOLOGY_IMAGE" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);
	
	ALTER TABLE "RADIOLOGY_OCCURRENCE" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "DOMAIN" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "CONCEPT_CLASS" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "CONCEPT_RELATIONSHIP" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "RELATIONSHIP" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "CONCEPT_SYNONYM" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "CONCEPT_ANCESTOR" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "SOURCE_TO_CONCEPT_MAP" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "DRUG_STRENGTH" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "COHORT_DEFINITION" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "ATTRIBUTE_DEFINITION" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "PERSON" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "OBSERVATION_PERIOD" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "SPECIMEN" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "DEATH" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "VISIT_OCCURRENCE" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "PROCEDURE_OCCURRENCE" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "DRUG_EXPOSURE" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "DEVICE_EXPOSURE" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "CONDITION_OCCURRENCE" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "MEASUREMENT" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "NOTE" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "NOTE_NLP" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "OBSERVATION" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "FACT_RELATIONSHIP" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "LOCATION" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "CARE_SITE" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "PROVIDER" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "PAYER_PLAN_PERIOD" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "COST" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "COHORT" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "COHORT_ATTRIBUTE" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "DRUG_ERA" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "DOSE_ERA" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "CONDITION_ERA" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "VISIT_DETAIL" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "SURVEY_CONDUCT" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	ALTER TABLE "CONCEPT_HIERARCHY" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

    ALTER TABLE "METADATA" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);

	--Add system versioning table

	ALTER TABLE "CONCEPT" ADD SYSTEM VERSIONING HISTORY TABLE "CONCEPT_HISTORY";
	
	ALTER TABLE "RADIOLOGY_IMAGE" ADD SYSTEM VERSIONING HISTORY TABLE "RADIOLOGY_IMAGE_HISTORY";
	
	ALTER TABLE "RADIOLOGY_OCCURRENCE" ADD SYSTEM VERSIONING HISTORY TABLE "RADIOLOGY_OCCURRENCE_HISTORY";
	
	ALTER TABLE "DOMAIN" ADD SYSTEM VERSIONING HISTORY TABLE "DOMAIN_HISTORY";
	
	ALTER TABLE "CONCEPT_CLASS" ADD SYSTEM VERSIONING HISTORY TABLE "CONCEPT_CLASS_HISTORY";
	
	ALTER TABLE "CONCEPT_RELATIONSHIP" ADD SYSTEM VERSIONING HISTORY TABLE "CONCEPT_RELATIONSHIP_HISTORY";
	
	ALTER TABLE "RELATIONSHIP" ADD SYSTEM VERSIONING HISTORY TABLE "RELATIONSHIP_HISTORY";
	
	ALTER TABLE "CONCEPT_SYNONYM" ADD SYSTEM VERSIONING HISTORY TABLE "CONCEPT_SYNONYM_HISTORY";
	
	ALTER TABLE "CONCEPT_ANCESTOR" ADD SYSTEM VERSIONING HISTORY TABLE "CONCEPT_ANCESTOR_HISTORY";
	
	ALTER TABLE "SOURCE_TO_CONCEPT_MAP" ADD SYSTEM VERSIONING HISTORY TABLE "SOURCE_TO_CONCEPT_MAP_HISTORY";
	
	ALTER TABLE "DRUG_STRENGTH" ADD SYSTEM VERSIONING HISTORY TABLE "DRUG_STRENGTH_HISTORY";
	
	ALTER TABLE "COHORT_DEFINITION" ADD SYSTEM VERSIONING HISTORY TABLE "COHORT_DEFINITION_HISTORY";
	
	ALTER TABLE "ATTRIBUTE_DEFINITION" ADD SYSTEM VERSIONING HISTORY TABLE "ATTRIBUTE_DEFINITION_HISTORY";
	
	ALTER TABLE "PERSON" ADD SYSTEM VERSIONING HISTORY TABLE "PERSON_HISTORY";
	
	ALTER TABLE "OBSERVATION_PERIOD" ADD SYSTEM VERSIONING HISTORY TABLE "OBSERVATION_PERIOD_HISTORY";
	
	ALTER TABLE "SPECIMEN" ADD SYSTEM VERSIONING HISTORY TABLE "SPECIMEN_HISTORY";
	
	ALTER TABLE "DEATH" ADD SYSTEM VERSIONING HISTORY TABLE "DEATH_HISTORY";
	
	ALTER TABLE "VISIT_OCCURRENCE" ADD SYSTEM VERSIONING HISTORY TABLE "VISIT_OCCURRENCE_HISTORY";
	
	ALTER TABLE "PROCEDURE_OCCURRENCE" ADD SYSTEM VERSIONING HISTORY TABLE "PROCEDURE_OCCURRENCE_HISTORY";
	
	ALTER TABLE "DRUG_EXPOSURE" ADD SYSTEM VERSIONING HISTORY TABLE "DRUG_EXPOSURE_HISTORY";
	
	ALTER TABLE "DEVICE_EXPOSURE" ADD SYSTEM VERSIONING HISTORY TABLE "DEVICE_EXPOSURE_HISTORY";
	
	ALTER TABLE "CONDITION_OCCURRENCE" ADD SYSTEM VERSIONING HISTORY TABLE "CONDITION_OCCURRENCE_HISTORY";
	
	ALTER TABLE "MEASUREMENT" ADD SYSTEM VERSIONING HISTORY TABLE "MEASUREMENT_HISTORY";
	
	ALTER TABLE "NOTE" ADD SYSTEM VERSIONING HISTORY TABLE "NOTE_HISTORY";
	
	ALTER TABLE "NOTE_NLP" ADD SYSTEM VERSIONING HISTORY TABLE "NOTE_NLP_HISTORY";
	
	ALTER TABLE "OBSERVATION" ADD SYSTEM VERSIONING HISTORY TABLE "OBSERVATION_HISTORY";
	
	ALTER TABLE "FACT_RELATIONSHIP" ADD SYSTEM VERSIONING HISTORY TABLE "FACT_RELATIONSHIP_HISTORY";
	
	ALTER TABLE "LOCATION" ADD SYSTEM VERSIONING HISTORY TABLE "LOCATION_HISTORY";
	
	ALTER TABLE "CARE_SITE" ADD SYSTEM VERSIONING HISTORY TABLE "CARE_SITE_HISTORY";
	
	ALTER TABLE "PROVIDER" ADD SYSTEM VERSIONING HISTORY TABLE "PROVIDER_HISTORY";
	
	ALTER TABLE "PAYER_PLAN_PERIOD" ADD SYSTEM VERSIONING HISTORY TABLE "PAYER_PLAN_PERIOD_HISTORY";
	
	ALTER TABLE "COST" ADD SYSTEM VERSIONING HISTORY TABLE "COST_HISTORY";
	
	ALTER TABLE "COHORT" ADD SYSTEM VERSIONING HISTORY TABLE "COHORT_HISTORY";
	
	ALTER TABLE "COHORT_ATTRIBUTE" ADD SYSTEM VERSIONING HISTORY TABLE "COHORT_ATTRIBUTE_HISTORY";
	
	ALTER TABLE "DRUG_ERA" ADD SYSTEM VERSIONING HISTORY TABLE "DRUG_ERA_HISTORY";
	
	ALTER TABLE "DOSE_ERA" ADD SYSTEM VERSIONING HISTORY TABLE "DOSE_ERA_HISTORY";
	
	ALTER TABLE "CONDITION_ERA" ADD SYSTEM VERSIONING HISTORY TABLE "CONDITION_ERA_HISTORY";
	
	ALTER TABLE "VISIT_DETAIL" ADD SYSTEM VERSIONING HISTORY TABLE "VISIT_DETAIL_HISTORY";
	
	ALTER TABLE "METADATA" ADD SYSTEM VERSIONING HISTORY TABLE "METADATA_HISTORY";
	
	ALTER TABLE "SURVEY_CONDUCT" ADD SYSTEM VERSIONING HISTORY TABLE "SURVEY_CONDUCT_HISTORY";
	
	ALTER TABLE "CONCEPT_HIERARCHY" ADD SYSTEM VERSIONING HISTORY TABLE "CONCEPT_HIERARCHY_HISTORY";

	
/*
	ALTER TABLE "CONCEPT" DROP SYSTEM VERSIONING
	ALTER TABLE "CONCEPT" DROP PERIOD FOR SYSTEM_TIME
	
	ALTER TABLE "RADIOLOGY_IMAGE" DROP SYSTEM VERSIONING
	ALTER TABLE "RADIOLOGY_IMAGE" DROP PERIOD FOR SYSTEM_TIME

	ALTER TABLE "RADIOLOGY_OCCURRENCE" DROP SYSTEM VERSIONING
	ALTER TABLE "RADIOLOGY_OCCURRENCE" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "DOMAIN" DROP SYSTEM VERSIONING
	ALTER TABLE "DOMAIN" DROP PERIOD FOR SYSTEM_TIME;
	
	ALTER TABLE "CONCEPT_CLASS" DROP SYSTEM VERSIONING
	ALTER TABLE "CONCEPT_CLASS" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "CONCEPT_RELATIONSHIP" DROP SYSTEM VERSIONING
	ALTER TABLE "CONCEPT_RELATIONSHIP" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "RELATIONSHIP" DROP SYSTEM VERSIONING
	ALTER TABLE "RELATIONSHIP" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "CONCEPT_SYNONYM" DROP SYSTEM VERSIONING
	ALTER TABLE "CONCEPT_SYNONYM" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "CONCEPT_ANCESTOR" DROP SYSTEM VERSIONING
	ALTER TABLE "CONCEPT_ANCESTOR" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "SOURCE_TO_CONCEPT_MAP" DROP SYSTEM VERSIONING
	ALTER TABLE "SOURCE_TO_CONCEPT_MAP" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "DRUG_STRENGTH" DROP SYSTEM VERSIONING
	ALTER TABLE "DRUG_STRENGTH" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "COHORT_DEFINITION" DROP SYSTEM VERSIONING
	ALTER TABLE "COHORT_DEFINITION" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "ATTRIBUTE_DEFINITION" DROP SYSTEM VERSIONING
	ALTER TABLE "ATTRIBUTE_DEFINITION" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "PERSON" DROP SYSTEM VERSIONING
	ALTER TABLE "PERSON" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "OBSERVATION_PERIOD" DROP SYSTEM VERSIONING
	ALTER TABLE "OBSERVATION_PERIOD" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "SPECIMEN" DROP SYSTEM VERSIONING
	ALTER TABLE "SPECIMEN" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "DEATH" DROP SYSTEM VERSIONING
	ALTER TABLE "DEATH" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "VISIT_OCCURRENCE" DROP SYSTEM VERSIONING
	ALTER TABLE "VISIT_OCCURRENCE" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "PROCEDURE_OCCURRENCE" DROP SYSTEM VERSIONING
	ALTER TABLE "PROCEDURE_OCCURRENCE" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "DRUG_EXPOSURE" DROP SYSTEM VERSIONING
	ALTER TABLE "DRUG_EXPOSURE" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "DEVICE_EXPOSURE" DROP SYSTEM VERSIONING
	ALTER TABLE "DEVICE_EXPOSURE" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "CONDITION_OCCURRENCE" DROP SYSTEM VERSIONING
	ALTER TABLE "CONDITION_OCCURRENCE" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "MEASUREMENT" DROP SYSTEM VERSIONING
	ALTER TABLE "MEASUREMENT" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "NOTE" DROP SYSTEM VERSIONING
	ALTER TABLE "NOTE" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "NOTE_NLP" DROP SYSTEM VERSIONING
	ALTER TABLE "NOTE_NLP" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "OBSERVATION" DROP SYSTEM VERSIONING
	ALTER TABLE "OBSERVATION" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "FACT_RELATIONSHIP" DROP SYSTEM VERSIONING
	ALTER TABLE "FACT_RELATIONSHIP" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "LOCATION" DROP SYSTEM VERSIONING
	ALTER TABLE "LOCATION" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "CARE_SITE" DROP SYSTEM VERSIONING
	ALTER TABLE "CARE_SITE" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "PROVIDER" DROP SYSTEM VERSIONING
	ALTER TABLE "PROVIDER" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "PAYER_PLAN_PERIOD" DROP SYSTEM VERSIONING
	ALTER TABLE "PAYER_PLAN_PERIOD" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "COST" DROP SYSTEM VERSIONING
	ALTER TABLE "COST" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "COHORT" DROP SYSTEM VERSIONING
	ALTER TABLE "COHORT" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "COHORT_ATTRIBUTE" DROP SYSTEM VERSIONING
	ALTER TABLE "COHORT_ATTRIBUTE" DROP PERIOD FOR SYSTEM_TIME;
	
	ALTER TABLE "DRUG_ERA" DROP SYSTEM VERSIONING
	ALTER TABLE "DRUG_ERA" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "DOSE_ERA" DROP SYSTEM VERSIONING
	ALTER TABLE "DOSE_ERA" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "CONDITION_ERA" DROP SYSTEM VERSIONING
	ALTER TABLE "CONDITION_ERA" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "VISIT_DETAIL" DROP SYSTEM VERSIONING
	ALTER TABLE "VISIT_DETAIL" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "SURVEY_CONDUCT" DROP SYSTEM VERSIONING
	ALTER TABLE "SURVEY_CONDUCT" DROP PERIOD FOR SYSTEM_TIME;

	ALTER TABLE "CONCEPT_HIERARCHY" DROP SYSTEM VERSIONING
	ALTER TABLE "CONCEPT_HIERARCHY" DROP PERIOD FOR SYSTEM_TIME;
	
*/
