--liquibase formatted sql
--changeset alp:V5.4.1.2.2__add_versioning_vocab_table.sql


CREATE COLUMN TABLE "VOCABULARY_HISTORY" AS 
(
    SELECT * FROM "VOCABULARY"
);

ALTER TABLE "VOCABULARY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);

ALTER TABLE "VOCABULARY_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

ALTER TABLE "VOCABULARY" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);
ALTER TABLE "VOCABULARY" ADD SYSTEM VERSIONING HISTORY TABLE "VOCABULARY_HISTORY";
