--liquibase formatted sql
--changeset alp:V5.4.1.1.1__apply_v5.4.sql labels:5.4 contexts:frankfurt


-- This changeset will update the OMOP tables in accordance with CDM Version 5.4
-- Please refer to http://ohdsi.github.io/CommonDataModel/cdm54Changes.html for list of changes


RENAME COLUMN "VISIT_OCCURRENCE"."ADMITTING_SOURCE_CONCEPT_ID" TO "ADMITTED_FROM_CONCEPT_ID";

RENAME COLUMN "VISIT_OCCURRENCE"."ADMITTING_SOURCE_VALUE" TO "ADMITTED_FROM_SOURCE_VALUE";

RENAME COLUMN "VISIT_OCCURRENCE"."DISCHARGE_TO_CONCEPT_ID" TO "DISCHARGED_TO_CONCEPT_ID";

RENAME COLUMN "VISIT_OCCURRENCE"."DISCHARGE_TO_SOURCE_VALUE" TO "DISCHARGED_TO_SOURCE_VALUE";


RENAME COLUMN "VISIT_DETAIL"."ADMITTING_SOURCE_CONCEPT_ID" TO "ADMITTED_FROM_CONCEPT_ID";

RENAME COLUMN "VISIT_DETAIL"."ADMITTING_SOURCE_VALUE" TO "ADMITTED_FROM_SOURCE_VALUE";

RENAME COLUMN "VISIT_DETAIL"."DISCHARGE_TO_CONCEPT_ID" TO "DISCHARGED_TO_CONCEPT_ID";

RENAME COLUMN "VISIT_DETAIL"."DISCHARGE_TO_SOURCE_VALUE" TO "DISCHARGED_TO_SOURCE_VALUE";

RENAME COLUMN "VISIT_DETAIL"."VISIT_DETAIL_PARENT_ID" TO "PARENT_VISIT_DETAIL_ID";


ALTER TABLE "PROCEDURE_OCCURRENCE" ADD (
	"PROCEDURE_END_DATE" DATE NULL,
	"PROCEDURE_END_DATETIME" TIMESTAMP NULL
);


ALTER TABLE "DEVICE_EXPOSURE" ALTER ("UNIQUE_DEVICE_ID" VARCHAR(255));


ALTER TABLE "DEVICE_EXPOSURE" ADD (
	"PRODUCTION_ID" VARCHAR(255) NULL,
	"UNIT_CONCEPT_ID" INTEGER NULL,
	"UNIT_SOURCE_VALUE" VARCHAR(50) NULL,
	"UNIT_SOURCE_CONCEPT_ID" INTEGER NULL
);


ALTER TABLE "MEASUREMENT" ADD (
	"UNIT_SOURCE_CONCEPT_ID" INTEGER NULL,
	"MEASUREMENT_EVENT_ID" INTEGER NULL,
	"MEAS_EVENT_FIELD_CONCEPT_ID" INTEGER NULL
);


ALTER TABLE "OBSERVATION" ADD (
	"VALUE_SOURCE_VALUE" VARCHAR(50) NULL
	--"OBSERVATION_EVENT_ID" INTEGER NULL,
	--"OBS_EVENT_FIELD_CONCEPT_ID" INTEGER NULL
);


ALTER TABLE "NOTE" ADD (
	"NOTE_EVENT_ID" INTEGER NULL,
	"NOTE_EVENT_FIELD_CONCEPT_ID" INTEGER NULL
) ;


ALTER TABLE "LOCATION" ADD (
	"COUNTRY_CONCEPT_ID" INTEGER NULL,
	"COUNTRY_SOURCE_VALUE" VARCHAR(80) NULL,
	"LATITUDE" NUMERIC NULL,
	"LONGITUDE" NUMERIC NULL
);


CREATE TABLE "EPISODE" (
	"EPISODE_ID" INTEGER NOT NULL,
	"PERSON_ID" INTEGER NOT NULL,
	"EPISODE_CONCEPT_ID" INTEGER NOT NULL,
	"EPISODE_START_DATE" DATE NOT NULL,
	"EPISODE_START_DATETIME" TIMESTAMP NULL,
	"EPISODE_END_DATE" DATE NULL,
	"EPISODE_END_DATETIME" TIMESTAMP NULL,
	"EPISODE_PARENT_ID" INTEGER NULL,
	"EPISODE_NUMBER" INTEGER NULL,
	"EPISODE_OBJECT_CONCEPT_ID" INTEGER NOT NULL,
	"EPISODE_TYPE_CONCEPT_ID" INTEGER NOT NULL,
	"EPISODE_SOURCE_VALUE" VARCHAR(50) NULL,
	"EPISODE_SOURCE_CONCEPT_ID" INTEGER NULL
);


CREATE TABLE "EPISODE_EVENT" (
	"EPISODE_ID" INTEGER NOT NULL,
	"EVENT_ID" INTEGER NOT NULL,
	"EPISODE_EVENT_FIELD_CONCEPT_ID" INTEGER NOT NULL
);


ALTER TABLE "METADATA" ADD (
	"METADATA_ID" INTEGER NOT NULL,
	"VALUE_AS_NUMBER" NUMERIC NULL
);


ALTER TABLE "CDM_SOURCE" ADD (
	"CDM_VERSION_CONCEPT_ID" INTEGER NOT NULL DEFAULT 0
);


ALTER TABLE "CDM_SOURCE" ALTER (
	"CDM_SOURCE_NAME" VARCHAR(255) NOT NULL,
	"CDM_SOURCE_ABBREVIATION" VARCHAR(25) NOT NULL,
	"CDM_HOLDER" VARCHAR(255) NOT NULL,
	"SOURCE_RELEASE_DATE" DATE NOT NULL,
	"CDM_RELEASE_DATE" DATE NOT NULL
);


ALTER TABLE "VOCABULARY" ALTER (
	"VOCABULARY_REFERENCE" VARCHAR(255) NULL,
	"VOCABULARY_VERSION" VARCHAR(255) NULL
);


/*
DROP TABLE "ATTRIBUTE_DEFINITION"


CREATE TABLE "COHORT" (
    "COHORT_DEFINITION_ID" INTEGER NOT NULL,
    "SUBJECT_ID" INTEGER NOT NULL,
    "COHORT_START_DATE" DATE NOT NULL,
    "COHORT_END_DATE" DATE NOT NULL
);


CREATE TABLE "COHORT_DEFINITION" (
	"COHORT_DEFINITION_ID" INTEGER NOT NULL,
	"COHORT_DEFINITION_NAME" VARCHAR(255) NOT NULL,
	"COHORT_DEFINITION_DESCRIPTION" TEXT NULL,
	"DEFINITION_TYPE_CONCEPT_ID" INTEGER NOT NULL,
	"COHORT_DEFINITION_SYNTAX" TEXT NULL,
	"SUBJECT_CONCEPT_ID INTEGER" NOT NULL,
	"COHORT_INITIATION_DATE" DATE NULL 
);
*/


--rollback RENAME COLUMN "VISIT_OCCURRENCE"."ADMITTED_FROM_CONCEPT_ID" TO "ADMITTING_SOURCE_CONCEPT_ID";
--rollback RENAME COLUMN "VISIT_OCCURRENCE"."ADMITTED_FROM_SOURCE_VALUE" TO "ADMITTING_SOURCE_VALUE";
--rollback RENAME COLUMN "VISIT_OCCURRENCE"."DISCHARGED_TO_CONCEPT_ID" TO "DISCHARGE_TO_CONCEPT_ID";
--rollback RENAME COLUMN "VISIT_OCCURRENCE"."DISCHARGED_TO_SOURCE_VALUE" TO "DISCHARGE_TO_SOURCE_VALUE";

--rollback RENAME COLUMN "VISIT_DETAIL"."ADMITTED_FROM_CONCEPT_ID" TO "ADMITTING_SOURCE_CONCEPT_ID";
--rollback RENAME COLUMN "VISIT_DETAIL"."ADMITTED_FROM_SOURCE_VALUE" TO "ADMITTING_SOURCE_VALUE";
--rollback RENAME COLUMN "VISIT_DETAIL"."DISCHARGED_TO_CONCEPT_ID" TO "DISCHARGE_TO_CONCEPT_ID";
--rollback RENAME COLUMN "VISIT_DETAIL"."DISCHARGED_TO_SOURCE_VALUE" TO "DISCHARGE_TO_SOURCE_VALUE";
--rollback RENAME COLUMN "VISIT_DETAIL"."PARENT_VISIT_DETAIL_ID" TO "VISIT_DETAIL_PARENT_ID";

--rollback ALTER TABLE "PROCEDURE_OCCURRENCE" DROP COLUMN "PROCEDURE_END_DATE";
--rollback ALTER TABLE "PROCEDURE_OCCURRENCE" DROP COLUMN "PROCEDURE_END_DATETIME";

--rollback ALTER TABLE "DEVICE_EXPOSURE" DROP COLUMN "PRODUCTION_ID";
--rollback ALTER TABLE "DEVICE_EXPOSURE" DROP COLUMN "UNIT_CONCEPT_ID";
--rollback ALTER TABLE "DEVICE_EXPOSURE" DROP COLUMN "UNIT_SOURCE_VALUE";
--rollback ALTER TABLE "DEVICE_EXPOSURE" DROP COLUMN "UNIT_SOURCE_CONCEPT_ID";

--rollback ALTER TABLE "MEASUREMENT" DROP COLUMN "UNIT_SOURCE_CONCEPT_ID";
--rollback ALTER TABLE "MEASUREMENT" DROP COLUMN "MEASUREMENT_EVENT_ID";
--rollback ALTER TABLE "MEASUREMENT" DROP COLUMN "MEAS_EVENT_FIELD_CONCEPT_ID";

--rollback ALTER TABLE "OBSERVATION" DROP COLUMN "VALUE_SOURCE_VALUE";

--rollback ALTER TABLE "NOTE" DROP COLUMN "NOTE_EVENT_ID";
--rollback ALTER TABLE "NOTE" DROP COLUMN "NOTE_EVENT_FIELD_CONCEPT_ID";

--rollback ALTER TABLE "LOCATION" DROP COLUMN "COUNTRY_CONCEPT_ID";
--rollback ALTER TABLE "LOCATION" DROP COLUMN "COUNTRY_SOURCE_VALUE";
--rollback ALTER TABLE "LOCATION" DROP COLUMN "LATITUDE";
--rollback ALTER TABLE "LOCATION" DROP COLUMN "LONGITUDE";

--rollback DROP TABLE "EPISODE";
--rollback DROP TABLE "EPISODE_EVENT";

--rollback ALTER TABLE "METADATA" DROP COLUMN "METADATA_ID";
--rollback ALTER TABLE "METADATA" DROP COLUMN "VALUE_AS_NUMBER";

--rollback ALTER TABLE "CDM_SOURCE" DROP COLUMN "CDM_VERSION_CONCEPT_ID";

--rollback ALTER TABLE "CDM_SOURCE" ALTER ("CDM_SOURCE_NAME" VARCHAR(255) NULL);
--rollback ALTER TABLE "CDM_SOURCE" ALTER ("CDM_SOURCE_ABBREVIATION" VARCHAR(25) NULL);
--rollback ALTER TABLE "CDM_SOURCE" ALTER ("CDM_HOLDER" VARCHAR(255) NULL);
--rollback ALTER TABLE "CDM_SOURCE" ALTER ("SOURCE_RELEASE_DATE" DATE NULL);
--rollback ALTER TABLE "CDM_SOURCE" ALTER ("CDM_RELEASE_DATE" DATE NULL);

--rollback ALTER TABLE "VOCABULARY" ALTER ("VOCABULARY_REFERENCE" VARCHAR(255) NOT NULL);
--rollback ALTER TABLE "VOCABULARY" ALTER ("VOCABULARY_VERSION" VARCHAR(255) NOT NULL);