--liquibase formatted sql
--changeset alp:V1.0.0.0.5_alter_omop_tables_column.sql


ALTER TABLE "COST"
RENAME COLUMN "REVEUE_CODE_SOURCE_VALUE" TO "REVENUE_CODE_SOURCE_VALUE";

ALTER TABLE "PAYER_PLAN_PERIOD"
ADD COLUMN "SPONSOR_SOURCE_VALUE" VARCHAR(50) NULL;


--rollback ALTER TABLE "COST" RENAME COLUMN "REVENUE_CODE_SOURCE_VALUE" TO "REVEUE_CODE_SOURCE_VALUE";
--rollback ALTER TABLE "PAYER_PLAN_PERIOD" DROP COLUMN "SPONSOR_SOURCE_VALUE";