--liquibase formatted sql
--changeset alp:V1.0.0.1.0__alter_table_add_versioning


-- QUESTIONNAIRE_RESPONSE
CREATE COLUMN TABLE "GDM.QUESTIONNAIRE_RESPONSE_HISTORY" AS 
(
    SELECT * FROM "GDM.QUESTIONNAIRE_RESPONSE"
);

ALTER TABLE "GDM.QUESTIONNAIRE_RESPONSE" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "GDM.QUESTIONNAIRE_RESPONSE_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- ITEM
CREATE COLUMN TABLE "GDM.ITEM_HISTORY" AS 
(
    SELECT * FROM "GDM.ITEM"
);

ALTER TABLE "GDM.ITEM" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "GDM.ITEM_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- ANSWER
CREATE COLUMN TABLE "GDM.ANSWER_HISTORY" AS 
(
    SELECT * FROM "GDM.ANSWER"
);

ALTER TABLE "GDM.ANSWER" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "GDM.ANSWER_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

ALTER TABLE "GDM.QUESTIONNAIRE_RESPONSE" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);
ALTER TABLE "GDM.QUESTIONNAIRE_RESPONSE" ADD SYSTEM VERSIONING HISTORY TABLE "GDM.QUESTIONNAIRE_RESPONSE_HISTORY";
ALTER TABLE "GDM.ITEM" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);
ALTER TABLE "GDM.ITEM" ADD SYSTEM VERSIONING HISTORY TABLE "GDM.ITEM_HISTORY";
ALTER TABLE "GDM.ANSWER" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);
ALTER TABLE "GDM.ANSWER" ADD SYSTEM VERSIONING HISTORY TABLE "GDM.ANSWER_HISTORY";
