--liquibase formatted sql
--changeset alp:V1.0.0.0.5__alter_research_subject_view
CREATE OR REPLACE VIEW "VIEW::GDM.RESEARCH_SUBJECT_BASE" AS
SELECT 
"ALP_ID",
"PERSON_ID",
"STATUS",
"PERIOD_START",	  
"PERIOD_END",
"STUDY_REFERENCE",
"STUDY_TYPE",
"STUDY_IDENTIFIER_USE",
"STUDY_IDENTIFIER_TYPE",
"STUDY_IDENTIFIER_SYSTEM",
"STUDY_IDENTIFIER_VALUE",
"STUDY_IDENTIFIER_PERIOD_START",
"STUDY_IDENTIFIER_PERIOD_END",
"STUDY_DISPLAY",
"INDIVIDUAL_REFERENCE",
"INDIVIDUAL_TYPE",
"INDIVIDUAL_IDENTIFIER_USE",
"INDIVIDUAL_IDENTIFIER_TYPE",
"INDIVIDUAL_IDENTIFIER_SYSTEM",
"INDIVIDUAL_IDENTIFIER_VALUE",
"INDIVIDUAL_IDENTIFIER_PERIOD_START",
"INDIVIDUAL_IDENTIFIER_PERIOD_END",
"INDIVIDUAL_DISPLAY",
"ASSIGNED_ARM",
"ACTUAL_ARM",
TO_DATE('9999-12-31', 'YYYY-MM-DD') AS "DUMMY_DATE_OF_BIRTH"
FROM "GDM.RESEARCH_SUBJECT"
WITH READ ONLY;

--rollback DROP VIEW "VIEW::GDM.RESEARCH_SUBJECT_BASE";