--liquibase formatted sql
--changeset alp:V5.3.1.2.5__alter_omop_view

CREATE OR REPLACE VIEW "VIEW::OMOP.COND_ICD10" AS
SELECT 
    "CONDITION"."PERSON_ID" AS "PATIENT_ID",
    "CONDITION"."CONDITION_OCCURRENCE_ID",
    "CONDITION"."CONDITION_START_DATE",
    "CONDITION"."CONDITION_END_DATE",
    "CONDITION"."VISIT_OCCURRENCE_ID",
    "CONDITION"."CONDITION_SOURCE_VALUE",
    "CONDITION"."CONDITION_TYPE_CONCEPT_ID",
    "CONDITION"."CONDITION_STATUS_CONCEPT_ID",
    "C1"."CONCEPT_NAME" AS "ICD10_CONDITION_SOURCE_VALUE_CONCEPT_NAME",
    "C2"."CONCEPT_NAME" AS "CONDITION_TYPE_CONCEPT_NAME",
    "C3"."CONCEPT_NAME" AS "CONDITION_STATUS_CONCEPT_NAME",
    "C1"."CONCEPT_CODE" AS "CONDITION_SOURCE_VALUE_CONCEPT_CODE",
    "C2"."CONCEPT_CODE" AS "CONDITION_TYPE_CONCEPT_CODE",
    "C3"."CONCEPT_CODE" AS "CONDITION_STATUS_CONCEPT_CODE"
FROM "CONDITION_OCCURRENCE" AS "CONDITION"
INNER JOIN "VIEW::OMOP.CONCEPT" AS "C1"
ON "CONDITION"."CONDITION_SOURCE_VALUE" = "C1"."CONCEPT_CODE"
AND "C1"."DOMAIN_ID" = 'Condition' AND "C1"."VOCABULARY_ID" = 'ICD10'
LEFT JOIN "VIEW::OMOP.CONCEPT" AS "C2"
ON "CONDITION"."CONDITION_TYPE_CONCEPT_ID" = "C2"."CONCEPT_ID"
LEFT JOIN "VIEW::OMOP.CONCEPT" AS "C3"
ON "CONDITION"."CONDITION_STATUS_CONCEPT_ID" = "C3"."CONCEPT_ID"
WITH READ ONLY;