--liquibase formatted sql
--changeset alp:V1.0.0.0.5__alter_table_add_versioning.sql

-- GDM.QUESTIONNAIRE
CREATE COLUMN TABLE "GDM.QUESTIONNAIRE_HISTORY" AS 
(
    SELECT * FROM "GDM.QUESTIONNAIRE"
);
ALTER TABLE "GDM.QUESTIONNAIRE" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "GDM.QUESTIONNAIRE_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- GDM.ITEM_QUESTIONNAIRE
CREATE COLUMN TABLE "GDM.ITEM_QUESTIONNAIRE_HISTORY" AS 
(
    SELECT * FROM "GDM.ITEM_QUESTIONNAIRE"
);

ALTER TABLE "GDM.ITEM_QUESTIONNAIRE" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "GDM.ITEM_QUESTIONNAIRE_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);


ALTER TABLE "GDM.QUESTIONNAIRE" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);
ALTER TABLE "GDM.QUESTIONNAIRE" ADD SYSTEM VERSIONING HISTORY TABLE "GDM.QUESTIONNAIRE_HISTORY";

ALTER TABLE "GDM.ITEM_QUESTIONNAIRE" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);
ALTER TABLE "GDM.ITEM_QUESTIONNAIRE" ADD SYSTEM VERSIONING HISTORY TABLE "GDM.ITEM_QUESTIONNAIRE_HISTORY";

