--liquibase formatted sql
--changeset alp:V1.0.0.1.4__alter_table_add_versioning.sql

CREATE COLUMN TABLE "GDM.RESEARCH_SUBJECT_HISTORY" AS 
(
    SELECT * FROM "GDM.RESEARCH_SUBJECT"
);

ALTER TABLE "GDM.RESEARCH_SUBJECT" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "GDM.RESEARCH_SUBJECT_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

ALTER TABLE "GDM.RESEARCH_SUBJECT" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);
ALTER TABLE "GDM.RESEARCH_SUBJECT" ADD SYSTEM VERSIONING HISTORY TABLE "GDM.RESEARCH_SUBJECT_HISTORY";

-- DO BEGIN
-- 	EXEC 'ALTER TABLE "GDM.RESEARCH_SUBJECT" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL)';
-- 	EXEC 'ALTER TABLE "GDM.RESEARCH_SUBJECT" ADD SYSTEM VERSIONING HISTORY TABLE "GDM.RESEARCH_SUBJECT_HISTORY"';
-- END
