--liquibase formatted sql
--changeset alp:V5.3.1.2.4__alter_omop_tables_column

ALTER TABLE "PERSON" ALTER ("PERSON_ID" BIGINT);
ALTER TABLE "PERSON" ALTER ("LOCATION_ID" BIGINT);
ALTER TABLE "PERSON" ALTER ("PROVIDER_ID" BIGINT);
ALTER TABLE "PERSON" ALTER ("CARE_SITE_ID" BIGINT);


ALTER TABLE "DEATH" ALTER ("PERSON_ID" BIGINT);


ALTER TABLE "OBSERVATION_PERIOD" ALTER ("OBSERVATION_PERIOD_ID" BIGINT);
ALTER TABLE "OBSERVATION_PERIOD" ALTER ("PERSON_ID" BIGINT);


ALTER TABLE "VISIT_OCCURRENCE" ALTER ("VISIT_OCCURRENCE_ID" BIGINT);
ALTER TABLE "VISIT_OCCURRENCE" ALTER ("PERSON_ID" BIGINT);
ALTER TABLE "VISIT_OCCURRENCE" ALTER ("PROVIDER_ID" BIGINT);
ALTER TABLE "VISIT_OCCURRENCE" ALTER ("CARE_SITE_ID" BIGINT);
ALTER TABLE "VISIT_OCCURRENCE" ALTER ("PRECEDING_VISIT_OCCURRENCE_ID" BIGINT);


ALTER TABLE "VISIT_DETAIL" ALTER ("VISIT_DETAIL_ID" BIGINT);
ALTER TABLE "VISIT_DETAIL" ALTER ("PERSON_ID" BIGINT);
ALTER TABLE "VISIT_DETAIL" ALTER ("PROVIDER_ID" BIGINT);
ALTER TABLE "VISIT_DETAIL" ALTER ("CARE_SITE_ID" BIGINT);
ALTER TABLE "VISIT_DETAIL" ALTER ("PRECEDING_VISIT_DETAIL_ID" BIGINT);
ALTER TABLE "VISIT_DETAIL" ALTER ("VISIT_DETAIL_PARENT_ID" BIGINT);
ALTER TABLE "VISIT_DETAIL" ALTER ("VISIT_OCCURRENCE_ID" BIGINT);


ALTER TABLE "CONDITION_OCCURRENCE" ALTER ("CONDITION_OCCURRENCE_ID" BIGINT);
ALTER TABLE "CONDITION_OCCURRENCE" ALTER ("PERSON_ID" BIGINT);
ALTER TABLE "CONDITION_OCCURRENCE" ALTER ("PROVIDER_ID" BIGINT);
ALTER TABLE "CONDITION_OCCURRENCE" ALTER ("VISIT_OCCURRENCE_ID" BIGINT);
ALTER TABLE "CONDITION_OCCURRENCE" ALTER ("VISIT_DETAIL_ID" BIGINT);


ALTER TABLE "DRUG_EXPOSURE" ALTER ("DRUG_EXPOSURE_ID" BIGINT);
ALTER TABLE "DRUG_EXPOSURE" ALTER ("PERSON_ID" BIGINT);
ALTER TABLE "DRUG_EXPOSURE" ALTER ("PROVIDER_ID" BIGINT);
ALTER TABLE "DRUG_EXPOSURE" ALTER ("VISIT_OCCURRENCE_ID" BIGINT);
ALTER TABLE "DRUG_EXPOSURE" ALTER ("VISIT_DETAIL_ID" BIGINT);


ALTER TABLE "PROCEDURE_OCCURRENCE" ALTER ("PROCEDURE_OCCURRENCE_ID" BIGINT);
ALTER TABLE "PROCEDURE_OCCURRENCE" ALTER ("PERSON_ID" BIGINT);
ALTER TABLE "PROCEDURE_OCCURRENCE" ALTER ("PROVIDER_ID" BIGINT);
ALTER TABLE "PROCEDURE_OCCURRENCE" ALTER ("VISIT_OCCURRENCE_ID" BIGINT);
ALTER TABLE "PROCEDURE_OCCURRENCE" ALTER ("VISIT_DETAIL_ID" BIGINT);


ALTER TABLE "DEVICE_EXPOSURE" ALTER ("DEVICE_EXPOSURE_ID" BIGINT);
ALTER TABLE "DEVICE_EXPOSURE" ALTER ("PERSON_ID" BIGINT);
ALTER TABLE "DEVICE_EXPOSURE" ALTER ("PROVIDER_ID" BIGINT);
ALTER TABLE "DEVICE_EXPOSURE" ALTER ("VISIT_OCCURRENCE_ID" BIGINT);
ALTER TABLE "DEVICE_EXPOSURE" ALTER ("VISIT_DETAIL_ID" BIGINT);


ALTER TABLE "MEASUREMENT" ALTER ("MEASUREMENT_ID" BIGINT);
ALTER TABLE "MEASUREMENT" ALTER ("PERSON_ID" BIGINT);
ALTER TABLE "MEASUREMENT" ALTER ("PROVIDER_ID" BIGINT);
ALTER TABLE "MEASUREMENT" ALTER ("VISIT_OCCURRENCE_ID" BIGINT);
ALTER TABLE "MEASUREMENT" ALTER ("VISIT_DETAIL_ID" BIGINT);


ALTER TABLE "OBSERVATION" ALTER ("OBSERVATION_ID" BIGINT);
ALTER TABLE "OBSERVATION" ALTER ("PERSON_ID" BIGINT);
ALTER TABLE "OBSERVATION" ALTER ("PROVIDER_ID" BIGINT);
ALTER TABLE "OBSERVATION" ALTER ("VISIT_OCCURRENCE_ID" BIGINT);
ALTER TABLE "OBSERVATION" ALTER ("VISIT_DETAIL_ID" BIGINT);
ALTER TABLE "OBSERVATION" ALTER ("OBSERVATION_EVENT_ID" BIGINT);


ALTER TABLE "NOTE" ALTER ("NOTE_ID" BIGINT);
ALTER TABLE "NOTE" ALTER ("PERSON_ID" BIGINT);
ALTER TABLE "NOTE" ALTER ("PROVIDER_ID" BIGINT);
ALTER TABLE "NOTE" ALTER ("VISIT_OCCURRENCE_ID" BIGINT);
ALTER TABLE "NOTE" ALTER ("VISIT_DETAIL_ID" BIGINT);


ALTER TABLE "NOTE_NLP" ALTER ("NOTE_NLP_ID" BIGINT);
ALTER TABLE "NOTE_NLP" ALTER ("NOTE_ID" BIGINT);

ALTER TABLE "SPECIMEN" ALTER ("SPECIMEN_ID" BIGINT);
ALTER TABLE "SPECIMEN" ALTER ("PERSON_ID" BIGINT);


ALTER TABLE "FACT_RELATIONSHIP" ALTER ("FACT_ID_1" BIGINT);
ALTER TABLE "FACT_RELATIONSHIP" ALTER ("FACT_ID_2" BIGINT);


ALTER TABLE "SURVEY_CONDUCT" ALTER ("SURVEY_CONDUCT_ID" BIGINT);
ALTER TABLE "SURVEY_CONDUCT" ALTER ("PERSON_ID" BIGINT);
ALTER TABLE "SURVEY_CONDUCT" ALTER ("PROVIDER_ID" BIGINT);
ALTER TABLE "SURVEY_CONDUCT" ALTER ("VISIT_OCCURRENCE_ID" BIGINT);
ALTER TABLE "SURVEY_CONDUCT" ALTER ("VISIT_DETAIL_ID" BIGINT);
ALTER TABLE "SURVEY_CONDUCT" ALTER ("RESPONSE_VISIT_OCCURRENCE_ID" BIGINT);


ALTER TABLE "LOCATION" ALTER ("LOCATION_ID" BIGINT);


ALTER TABLE "CARE_SITE" ALTER ("CARE_SITE_ID" BIGINT);
ALTER TABLE "CARE_SITE" ALTER ("LOCATION_ID" BIGINT);


ALTER TABLE "PROVIDER" ALTER ("PROVIDER_ID" BIGINT);
ALTER TABLE "PROVIDER" ALTER ("CARE_SITE_ID" BIGINT);


ALTER TABLE "PAYER_PLAN_PERIOD" ALTER ("PAYER_PLAN_PERIOD_ID" BIGINT);
ALTER TABLE "PAYER_PLAN_PERIOD" ALTER ("PERSON_ID" BIGINT);


ALTER TABLE "COST" ALTER ("COST_ID" BIGINT);
ALTER TABLE "COST" ALTER ("COST_EVENT_ID" BIGINT);


ALTER TABLE "DRUG_ERA" ALTER ("DRUG_ERA_ID" BIGINT);
ALTER TABLE "DRUG_ERA" ALTER ("PERSON_ID" BIGINT);


ALTER TABLE "DOSE_ERA" ALTER ("DOSE_ERA_ID" BIGINT);
ALTER TABLE "DOSE_ERA" ALTER ("PERSON_ID" BIGINT);


ALTER TABLE "CONDITION_ERA" ALTER ("CONDITION_ERA_ID" BIGINT);
ALTER TABLE "CONDITION_ERA" ALTER ("PERSON_ID" BIGINT);


ALTER TABLE "RADIOLOGY_IMAGE" ALTER ("PERSON_ID" BIGINT);


ALTER TABLE "RADIOLOGY_OCCURRENCE" ALTER ("PERSON_ID" BIGINT);
ALTER TABLE "RADIOLOGY_OCCURRENCE" ALTER ("VISIT_OCCURRENCE_ID" BIGINT);
