--liquibase formatted sql
--changeset alp:V5.3.1.3.1__modify_omop_vocab_cols.sql

ALTER TABLE "CONCEPT" ALTER ("CONCEPT_NAME" NVARCHAR(1000));

ALTER TABLE "CONCEPT_SYNONYM" ALTER ("CONCEPT_SYNONYM_NAME" NVARCHAR(2000));

ALTER TABLE "DRUG_STRENGTH" ALTER ("AMOUNT_VALUE" DECIMAL(30,12));
ALTER TABLE "DRUG_STRENGTH" ALTER ("NUMERATOR_VALUE" DECIMAL(30,12));
ALTER TABLE "DRUG_STRENGTH" ALTER ("DENOMINATOR_VALUE" DECIMAL(30,12));