--liquibase formatted sql
--changeset alp:V5.3.1.2.8__modify_omop_attributes.sql

ALTER TABLE "CARE_SITE" ALTER ("CARE_SITE_NAME" NVARCHAR(300));
ALTER TABLE "CARE_SITE" ALTER ("CARE_SITE_SOURCE_VALUE" NVARCHAR(300));
ALTER TABLE "CARE_SITE" ALTER ("PLACE_OF_SERVICE_SOURCE_VALUE" NVARCHAR(300));

ALTER TABLE "CONDITION_OCCURRENCE" ALTER ("CONDITION_SOURCE_VALUE" NVARCHAR(200));
ALTER TABLE "CONDITION_OCCURRENCE" ALTER ("STOP_REASON" NVARCHAR(300));
ALTER TABLE "CONDITION_OCCURRENCE" ALTER ("CONDITION_STATUS_SOURCE_VALUE" NVARCHAR(50));

ALTER TABLE "COST" ALTER ("AMOUNT_ALLOWED" DECIMAL(18,2));
ALTER TABLE "COST" ALTER ("PAID_BY_PATIENT" DECIMAL(18,2));
ALTER TABLE "COST" ALTER ("PAID_BY_PAYER" DECIMAL(18,2));
ALTER TABLE "COST" ALTER ("PAID_BY_PRIMARY" DECIMAL(18,2));
ALTER TABLE "COST" ALTER ("PAID_DISPENSING_FEE" DECIMAL(18,2));
ALTER TABLE "COST" ALTER ("PAID_INGREDIENT_COST" DECIMAL(18,2));
ALTER TABLE "COST" ALTER ("PAID_PATIENT_COINSURANCE" DECIMAL(18,2));
ALTER TABLE "COST" ALTER ("PAID_PATIENT_COPAY" DECIMAL(18,2));
ALTER TABLE "COST" ALTER ("PAID_PATIENT_DEDUCTIBLE" DECIMAL(18,2));
ALTER TABLE "COST" ALTER ("TOTAL_CHARGE" DECIMAL(18,2));
ALTER TABLE "COST" ALTER ("TOTAL_COST" DECIMAL(18,2));
ALTER TABLE "COST" ALTER ("TOTAL_PAID" DECIMAL(18,2));

ALTER TABLE "COST" ALTER ("COST_DOMAIN_ID" NVARCHAR(50));
ALTER TABLE "COST" ALTER ("REVEUE_CODE_SOURCE_VALUE" NVARCHAR(100));
ALTER TABLE "COST" ALTER ("DRG_SOURCE_VALUE" NVARCHAR(3));

ALTER TABLE "DEATH" ALTER ("CAUSE_SOURCE_CONCEPT_ID" BIGINT);
ALTER TABLE "DEATH" ALTER ("CAUSE_SOURCE_VALUE" NVARCHAR(100));

ALTER TABLE "DEVICE_EXPOSURE" ALTER ("DEVICE_SOURCE_VALUE" NVARCHAR(300));
ALTER TABLE "DEVICE_EXPOSURE" ALTER ("UNIQUE_DEVICE_ID" NVARCHAR(50));

ALTER TABLE "DOSE_ERA" ALTER ("DOSE_VALUE" DECIMAL(18,5));

ALTER TABLE "DRUG_EXPOSURE" ALTER ("DOSE_UNIT_SOURCE_VALUE" NVARCHAR(300));
ALTER TABLE "DRUG_EXPOSURE" ALTER ("DRUG_SOURCE_VALUE" NVARCHAR(300));
ALTER TABLE "DRUG_EXPOSURE" ALTER ("QUANTITY" DECIMAL(18,5));
ALTER TABLE "DRUG_EXPOSURE" ALTER ("ROUTE_SOURCE_VALUE" NVARCHAR(300));
ALTER TABLE "DRUG_EXPOSURE" ALTER ("STOP_REASON" NVARCHAR(300));
ALTER TABLE "DRUG_EXPOSURE" ALTER ("LOT_NUMBER" NVARCHAR(50));

ALTER TABLE "DRUG_STRENGTH" ALTER ("AMOUNT_VALUE" DECIMAL(27,12));
ALTER TABLE "DRUG_STRENGTH" ALTER ("DENOMINATOR_VALUE" DECIMAL(27,12));
ALTER TABLE "DRUG_STRENGTH" ALTER ("NUMERATOR_VALUE" DECIMAL(27,12));
ALTER TABLE "DRUG_STRENGTH" ALTER ("INVALID_REASON" NVARCHAR(1));

ALTER TABLE "LOCATION" ALTER ("ADDRESS_1" NVARCHAR(150));
ALTER TABLE "LOCATION" ALTER ("ADDRESS_2" NVARCHAR(150));
ALTER TABLE "LOCATION" ALTER ("CITY" NVARCHAR(300));
ALTER TABLE "LOCATION" ALTER ("COUNTY" NVARCHAR(300));
ALTER TABLE "LOCATION" ALTER ("STATE" NVARCHAR(2));
ALTER TABLE "LOCATION" ALTER ("ZIP" NVARCHAR(9));
ALTER TABLE "LOCATION" ALTER ("LOCATION_SOURCE_VALUE" NVARCHAR(50));

ALTER TABLE "MEASUREMENT" ALTER ("MEASUREMENT_SOURCE_VALUE" NVARCHAR(300));
ALTER TABLE "MEASUREMENT" ALTER ("RANGE_HIGH" DECIMAL(18,5));
ALTER TABLE "MEASUREMENT" ALTER ("RANGE_LOW" DECIMAL(18,5));
ALTER TABLE "MEASUREMENT" ALTER ("UNIT_SOURCE_VALUE" NVARCHAR(300));
ALTER TABLE "MEASUREMENT" ALTER ("VALUE_AS_NUMBER" DECIMAL(18,5));
ALTER TABLE "MEASUREMENT" ALTER ("VALUE_SOURCE_VALUE" NVARCHAR(300));

ALTER TABLE "METADATA" ALTER ("NAME" NVARCHAR(250));

ALTER TABLE "NOTE" ALTER ("NOTE_TITLE" NVARCHAR(250));
ALTER TABLE "NOTE" ALTER ("NOTE_SOURCE_VALUE" NVARCHAR(50));

ALTER TABLE "NOTE_NLP" ALTER ("OFFSET" NVARCHAR(250));
ALTER TABLE "NOTE_NLP" ALTER ("NLP_SYSTEM" NVARCHAR(250));
ALTER TABLE "NOTE_NLP" ALTER ("SNIPPET" NVARCHAR(250));
ALTER TABLE "NOTE_NLP" ALTER ("TERM_EXISTS" NVARCHAR(1));
ALTER TABLE "NOTE_NLP" ALTER ("TERM_MODIFIERS" NVARCHAR(2000));
ALTER TABLE "NOTE_NLP" ALTER ("TERM_TEMPORAL" NVARCHAR(50));

ALTER TABLE "OBSERVATION" ALTER ("OBSERVATION_SOURCE_VALUE" NVARCHAR(300));
ALTER TABLE "OBSERVATION" ALTER ("OBSERVATION_SOURCE_VALUE" NVARCHAR(300));
ALTER TABLE "OBSERVATION" ALTER ("QUALIFIER_SOURCE_VALUE" NVARCHAR(400));
ALTER TABLE "OBSERVATION" ALTER ("UNIT_SOURCE_VALUE" NVARCHAR(400));
ALTER TABLE "OBSERVATION" ALTER ("VALUE_AS_NUMBER" DECIMAL(18,5));
ALTER TABLE "OBSERVATION" ALTER ("VALUE_AS_STRING" NVARCHAR(500));

ALTER TABLE "PAYER_PLAN_PERIOD" ALTER ("FAMILY_SOURCE_VALUE" NVARCHAR(50));
ALTER TABLE "PAYER_PLAN_PERIOD" ALTER ("PAYER_SOURCE_VALUE" NVARCHAR(50));
ALTER TABLE "PAYER_PLAN_PERIOD" ALTER ("PLAN_SOURCE_VALUE" NVARCHAR(50));
ALTER TABLE "PAYER_PLAN_PERIOD" ALTER ("STOP_REASON_SOURCE_VALUE" NVARCHAR(50));

ALTER TABLE "PERSON" ALTER ("ETHNICITY_SOURCE_VALUE" NVARCHAR(300));
ALTER TABLE "PERSON" ALTER ("GENDER_SOURCE_VALUE" NVARCHAR(300));
ALTER TABLE "PERSON" ALTER ("RACE_SOURCE_VALUE" NVARCHAR(300));
ALTER TABLE "PERSON" ALTER ("PERSON_SOURCE_VALUE" NVARCHAR(50));

ALTER TABLE "PROCEDURE_OCCURRENCE" ALTER ("PROCEDURE_SOURCE_VALUE" NVARCHAR(300));
ALTER TABLE "PROCEDURE_OCCURRENCE" ALTER ("MODIFIER_SOURCE_VALUE" NVARCHAR(50));

ALTER TABLE "PROVIDER" ALTER ("DEA" NVARCHAR(50));
ALTER TABLE "PROVIDER" ALTER ("GENDER_SOURCE_VALUE" NVARCHAR(300));
ALTER TABLE "PROVIDER" ALTER ("NPI" NVARCHAR(50));
ALTER TABLE "PROVIDER" ALTER ("SPECIALTY_SOURCE_VALUE" NVARCHAR(300));
ALTER TABLE "PROVIDER" ALTER ("PROVIDER_SOURCE_VALUE" NVARCHAR(50));
ALTER TABLE "PROVIDER" ALTER ("PROVIDER_NAME" NVARCHAR(255));

ALTER TABLE "SPECIMEN" ALTER ("ANATOMIC_SITE_SOURCE_VALUE" NVARCHAR(300));
ALTER TABLE "SPECIMEN" ALTER ("DISEASE_STATUS_SOURCE_VALUE" NVARCHAR(300));
ALTER TABLE "SPECIMEN" ALTER ("QUANTITY" DECIMAL(18,5));
ALTER TABLE "SPECIMEN" ALTER ("SPECIMEN_SOURCE_VALUE" NVARCHAR(300));
ALTER TABLE "SPECIMEN" ALTER ("UNIT_SOURCE_VALUE" NVARCHAR(300));
ALTER TABLE "SPECIMEN" ALTER ("SPECIMEN_SOURCE_ID" NVARCHAR(50));

ALTER TABLE "VISIT_DETAIL" ALTER ("ADMITTING_SOURCE_VALUE" NVARCHAR(300));
ALTER TABLE "VISIT_DETAIL" ALTER ("DISCHARGE_TO_SOURCE_VALUE" NVARCHAR(300));
ALTER TABLE "VISIT_DETAIL" ALTER ("VISIT_DETAIL_SOURCE_VALUE" NVARCHAR(300));

ALTER TABLE "VISIT_OCCURRENCE" ALTER ("ADMITTING_SOURCE_VALUE" NVARCHAR(300));
ALTER TABLE "VISIT_OCCURRENCE" ALTER ("DISCHARGE_TO_SOURCE_VALUE" NVARCHAR(300));
ALTER TABLE "VISIT_OCCURRENCE" ALTER ("VISIT_SOURCE_VALUE" NVARCHAR(300));
