--liquibase formatted sql
--changeset alp:V1.0.0.0.1_create_eav_tables


CREATE TABLE DICOM_IMAGE_METADATA(
    METADATA_ID INTEGER NOT NULL,
    METADATA_DATE DATE NOT NULL,
    METADATA_DATETIME TIMESTAMP,
    DATA_ELEMENT_TAG INTEGER NOT NULL,
    DATA_ELEMENT_SOURCE_NAME NVARCHAR(255) NOT NULL,
    DATA_ELEMENT_SOURCE_TAG NVARCHAR(255) NOT NULL,
    DATA_ELEMENT_SOURCE_GROUP_NUMBER NVARCHAR(255) NOT NULL,
    DATA_ELEMENT_SOURCE_VALUE_REPRESENTATION NVARCHAR(255) NOT NULL,
    IS_SEQUENCE BOOLEAN NOT NULL,
    PARENT_SEQUENCE_ID INTEGER,
    VALUE_AS_INTEGER INTEGER,
    VALUE_AS_NUMERIC NUMERIC,
    VALUE_AS_STRING NVARCHAR(5000),
    VALUE_AS_DATETIME TIMESTAMP,
    VALUE_AS_TEXT TEXT,
    DATA_ELEMENT_SOURCE_VALUE TEXT NOT NULL,
    IMAGE_OCCURRENCE_ID INTEGER NOT NULL
);


CREATE TABLE DICOM_DATA_ELEMENT(
    DATA_ELEMENT_TAG NVARCHAR(255) NOT NULL,
    DATA_ELEMENT_NAME NVARCHAR(255) NOT NULL,
    DATA_ELEMENT_KEYWORD NVARCHAR(255) NOT NULL,
    VALUE_REPRESENTATION NVARCHAR(255) NOT NULL,
    VALUE_MULTIPLICITY NVARCHAR(255) NOT NULL,
    DELIMITER NVARCHAR(255),
    DEPRECATED BOOLEAN
);


--rollback DROP TABLE DICOM_IMAGE_METADATA;
--rollback DROP TABLE DICOM_DATA_ELEMENT;