--liquibase formatted sql
--changeset alp:V1.0.0.0.7__alter_table_add_versioning.sql

-- GDM.CONSENT
CREATE COLUMN TABLE "GDM.CONSENT_HISTORY" AS 
(
    SELECT * FROM "GDM.CONSENT"
);

ALTER TABLE "GDM.CONSENT" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "GDM.CONSENT_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- GDM.CONSENT_DETAIL
CREATE COLUMN TABLE "GDM.CONSENT_DETAIL_HISTORY" AS 
(
    SELECT * FROM "GDM.CONSENT_DETAIL"
);

ALTER TABLE "GDM.CONSENT_DETAIL" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "GDM.CONSENT_DETAIL_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);
-- GDM.CONSENT_VALUE
CREATE COLUMN TABLE "GDM.CONSENT_VALUE_HISTORY" AS 
(
    SELECT * FROM "GDM.CONSENT_VALUE"
);

ALTER TABLE "GDM.CONSENT_VALUE" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "GDM.CONSENT_VALUE_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

ALTER TABLE "GDM.CONSENT" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);
ALTER TABLE "GDM.CONSENT" ADD SYSTEM VERSIONING HISTORY TABLE "GDM.CONSENT_HISTORY";

ALTER TABLE "GDM.CONSENT_DETAIL" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);
ALTER TABLE "GDM.CONSENT_DETAIL" ADD SYSTEM VERSIONING HISTORY TABLE "GDM.CONSENT_DETAIL_HISTORY";

ALTER TABLE "GDM.CONSENT_VALUE" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);
ALTER TABLE "GDM.CONSENT_VALUE" ADD SYSTEM VERSIONING HISTORY TABLE "GDM.CONSENT_VALUE_HISTORY";
