--liquibase formatted sql
--changeset alp:V5.4.1.2.0__drop_radiology_tables

DROP TABLE "RADIOLOGY_IMAGE" CASCADE; 

DROP TABLE "RADIOLOGY_IMAGE_HISTORY" CASCADE; 

DROP TABLE "RADIOLOGY_OCCURRENCE" CASCADE;

DROP TABLE "RADIOLOGY_OCCURRENCE_HISTORY" CASCADE;