--liquibase formatted sql
--changeset alp:V5.4.1.1.7_alter_concept_table.sql

ALTER TABLE CONCEPT DROP SYSTEM VERSIONING;

ALTER TABLE CONCEPT ALTER (CONCEPT_NAME NVARCHAR(1000) FUZZY SEARCH INDEX ON);
ALTER TABLE CONCEPT_HISTORY ALTER (CONCEPT_NAME NVARCHAR(1000) FUZZY SEARCH INDEX ON);

CREATE FULLTEXT INDEX index_on_concept_name ON CONCEPT(CONCEPT_NAME);
CREATE FULLTEXT INDEX index_on_concept_name_history ON CONCEPT_HISTORY(CONCEPT_NAME);

CREATE FULLTEXT INDEX index_on_concept_code ON CONCEPT(CONCEPT_CODE);
CREATE FULLTEXT INDEX index_on_concept_code_history ON CONCEPT_HISTORY(CONCEPT_CODE);

CREATE FULLTEXT INDEX index_on_concept_class_id ON CONCEPT(CONCEPT_CLASS_ID);
CREATE FULLTEXT INDEX index_on_concept_class_id_history ON CONCEPT_HISTORY(CONCEPT_CLASS_ID);

ALTER TABLE "CONCEPT" ADD SYSTEM VERSIONING HISTORY TABLE "CONCEPT_HISTORY";
