--liquibase formatted sql
--changeset alp:V1.0.0.0.0__create_consent_base_views
CREATE OR REPLACE VIEW "VIEW::GDM.CONSENT_BASE" AS
SELECT 
"C"."ID",
"C"."PERSON_ID", 
"C"."STATUS", 
"C"."CREATED_AT", 
"CD"."ID" AS "CONSENT_DETAIL_ID", 
"CD"."PARENT_CONSENT_DETAIL_ID",
"CD"."TYPE",
"CV"."ATTRIBUTE_GROUP_ID", 
"CV"."ATTRIBUTE", 
"CV"."VALUE" 
FROM "GDM.CONSENT" AS "C"
INNER JOIN "GDM.CONSENT_DETAIL" AS "CD"
ON "C"."ID" = "CD"."GDM_CONSENT_ID" 
INNER JOIN "GDM.CONSENT_VALUE" AS "CV"
ON "CV"."GDM_CONSENT_DETAIL_ID" = "CD"."ID";

--rollback DROP VIEW "VIEW::GDM.CONSENT_BASE";