--liquibase formatted sql
--changeset alp:V1.0.0.0.1__alter_table_add_versioning.sql

-- BI.EVENT
CREATE COLUMN TABLE "BI.EVENT_HISTORY" AS 
(
    SELECT * FROM "BI.EVENT"
);
ALTER TABLE "BI.EVENT" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "BI.EVENT_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

-- BI.EVENT_DATA
CREATE COLUMN TABLE "BI.EVENT_DATA_HISTORY" AS 
(
    SELECT * FROM "BI.EVENT_DATA"
);
ALTER TABLE "BI.EVENT_DATA" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "BI.EVENT_DATA_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

ALTER TABLE "BI.EVENT" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);
ALTER TABLE "BI.EVENT" ADD SYSTEM VERSIONING HISTORY TABLE "BI.EVENT_HISTORY";
ALTER TABLE "BI.EVENT_DATA" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);
ALTER TABLE "BI.EVENT_DATA" ADD SYSTEM VERSIONING HISTORY TABLE "BI.EVENT_DATA_HISTORY";



