--liquibase formatted sql
--changeset alp:V5.3.1.2.2__obs_view_with_event_id

CREATE OR REPLACE VIEW "VIEW::OMOP.OBS" (
    "OBSERVATION_ID",
    "PATIENT_ID",
    "OBSERVATION_CONCEPT_ID",
    "OBSERVATION_NAME",
    "OBSERVATION_DATE",
    "OBSERVATION_DATETIME",
    "OBSERVATION_TYPE_CONCEPT_ID",
    "OBSERVATION_TYPE_NAME",
    "VALUE_AS_NUMBER",
    "VALUE_AS_STRING",
    "VALUE_AS_CONCEPT_ID",
    "VALUE_NAME",
    "QUALIFIER_CONCEPT_ID",
    "QUALIFIER_NAME",
    "UNIT_CONCEPT_ID",
    "UNIT_NAME",
    "PROVIDER_ID",
    "VISIT_OCCURRENCE_ID",
    "OBSERVATION_SOURCE_VALUE",
    "OBSERVATION_SOURCE_CONCEPT_ID",
    "UNIT_SOURCE_VALUE",
    "QUALIFIER_SOURCE_VALUE",
    "OBSERVATION_CONCEPT_CODE",
    "OBSERVATION_TYPE_CONCEPT_CODE",
    "VALUE_AS_CONCEPT_CODE",
    "QUALIFIER_CONCEPT_CODE",
    "UNIT_CONCEPT_CODE",
    "OBSERVATION_EVENT_ID"
  ) AS
SELECT
  "o_$0"."OBSERVATION_ID",
  "o_$0"."PERSON_ID" AS "PATIENT_ID",
  "o_$0"."OBSERVATION_CONCEPT_ID",
  "c_$1"."CONCEPT_NAME" AS "OBSERVATION_NAME",
  "o_$0"."OBSERVATION_DATE",
  "o_$0"."OBSERVATION_DATETIME",
  "o_$0"."OBSERVATION_TYPE_CONCEPT_ID",
  "t_$2"."CONCEPT_NAME" AS "OBSERVATION_TYPE_NAME",
  "o_$0"."VALUE_AS_NUMBER",
  "o_$0"."VALUE_AS_STRING",
  "o_$0"."VALUE_AS_CONCEPT_ID",
  "v_$3"."CONCEPT_NAME" AS "VALUE_NAME",
  "o_$0"."QUALIFIER_CONCEPT_ID",
  "q_$4"."CONCEPT_NAME" AS "QUALIFIER_NAME",
  "o_$0"."UNIT_CONCEPT_ID",
  "u_$5"."CONCEPT_NAME" AS "UNIT_NAME",
  "o_$0"."PROVIDER_ID",
  "o_$0"."VISIT_OCCURRENCE_ID",
  "o_$0"."OBSERVATION_SOURCE_VALUE",
  "o_$0"."OBSERVATION_SOURCE_CONCEPT_ID",
  "o_$0"."UNIT_SOURCE_VALUE",
  "o_$0"."QUALIFIER_SOURCE_VALUE",
  "c_$1"."CONCEPT_CODE" AS "OBSERVATION_CONCEPT_CODE",
  "t_$2"."CONCEPT_CODE" AS "OBSERVATION_TYPE_CONCEPT_CODE",
  "v_$3"."CONCEPT_CODE" AS "VALUE_AS_CONCEPT_CODE",
  "q_$4"."CONCEPT_CODE" AS "QUALIFIER_CONCEPT_CODE",
  "u_$5"."CONCEPT_CODE" AS "UNIT_CONCEPT_CODE",
  "o_$0"."OBSERVATION_EVENT_ID"
FROM
  (
    (
      (
        (
          (
            "OBSERVATION" AS "o_$0"
            LEFT OUTER JOIN "CONCEPT" AS "c_$1" ON (
              "c_$1"."CONCEPT_ID" = "o_$0"."OBSERVATION_CONCEPT_ID"
            )
          )
          LEFT OUTER JOIN "CONCEPT" AS "t_$2" ON (
            "t_$2"."CONCEPT_ID" = "o_$0"."OBSERVATION_TYPE_CONCEPT_ID"
          )
        )
        LEFT OUTER JOIN "CONCEPT" AS "v_$3" ON (
          "v_$3"."CONCEPT_ID" = "o_$0"."VALUE_AS_CONCEPT_ID"
        )
      )
      LEFT OUTER JOIN "CONCEPT" AS "q_$4" ON (
        "q_$4"."CONCEPT_ID" = "o_$0"."QUALIFIER_CONCEPT_ID"
      )
    )
    LEFT OUTER JOIN "CONCEPT" AS "u_$5" ON ("u_$5"."CONCEPT_ID" = "o_$0"."UNIT_CONCEPT_ID")
  )
WITH READ ONLY;