--liquibase formatted sql
--changeset alp:V5.3.1.3.6_create_concept_hierarchy_table.sql
CREATE TABLE CONCEPT_HIERARCHY (
  CONCEPT_ID INTEGER NOT NULL,
  CONCEPT_NAME VARCHAR(1000) NOT NULL,
  DOMAIN_NAME VARCHAR(100) NOT NULL,
  LEVEL3_CONCEPT_NAME VARCHAR(1000),
  LEVEL2_CONCEPT_NAME VARCHAR(1000),
  LEVEL1_CONCEPT_NAME VARCHAR(1000)
);