--liquibase formatted sql
--changeset alp:V1.0.0.0.0__create_medical_imaging_tables


CREATE TABLE IMAGE_OCCURRENCE(
  IMAGE_OCCURRENCE_ID INTEGER NOT NULL,
  PERSON_ID INTEGER NOT NULL,
  PROCEDURE_OCCURRENCE_ID INTEGER NOT NULL,
  VISIT_OCCURRENCE_ID INTEGER,
  ANATOMIC_SITE_CONCEPT_ID INTEGER,
  WADORS_URI TEXT,
  LOCAL_PATH TEXT,
  IMAGE_OCCURRENCE_DATE DATE NOT NULL,
  IMAGE_STUDY_UID NVARCHAR(250) NOT NULL,
  IMAGE_SERIES_UID NVARCHAR(250) NOT NULL,
  MODALITY_CONCEPT_ID INTEGER NOT NULL
);


CREATE TABLE IMAGE_FEATURE(
  IMAGE_FEATURE_ID INTEGER NOT NULL,
  PERSON_ID INTEGER NOT NULL,
  IMAGE_OCCURRENCE_ID INTEGER NOT NULL,
  IMAGE_FEATURE_EVENT_FIELD_CONCEPT_ID INTEGER,
  IMAGE_FEATURE_EVENT_ID INTEGER,
  IMAGE_FEATURE_CONCEPT_ID INTEGER NOT NULL,
  IMAGE_FEATURE_TYPE_CONCEPT_ID INTEGER NOT NULL,
  IMAGE_FINDING_CONCEPT_ID INTEGER,
  IMAGE_FINDING_ID INTEGER,
  ANATOMIC_SITE_CONCEPT_ID INTEGER,
  ALG_SYSTEM TEXT,
  ALG_DATETIME TIMESTAMP
);


--rollback DROP TABLE IMAGE_OCCURRENCE;
--rollback DROP TABLE IMAGE_FEATURE;