--liquibase formatted sql
--changeset alp:V1.0.0.0.2_recreate_eav_tables


DROP TABLE DICOM_IMAGE_METADATA CASCADE;
DROP TABLE DICOM_DATA_ELEMENT CASCADE;


-- RENAME DICOM_IMAGE_METADATA TO DICOM_FILE_METADATA
CREATE TABLE DICOM_FILE_METADATA(
    METADATA_ID NVARCHAR(255) NOT NULL,
    DATA_ELEMENT_ID BIGINT,
    METADATA_SOURCE_KEYWORD NVARCHAR(255),
    METADATA_SOURCE_TAG NVARCHAR(20) NOT NULL,
    METADATA_SOURCE_GROUP_NUMBER NVARCHAR(20),
    METADATA_SOURCE_VALUE_REPRESENTATION NVARCHAR(20),
    METADATA_SOURCE_VALUE_MULTIPLICITY NVARCHAR(20),
    METADATA_SOURCE_VALUE TEXT,
    IS_SEQUENCE BOOLEAN,
    SEQUENCE_LENGTH INTEGER,
    PARENT_SEQUENCE_ID NVARCHAR(255),
    PARENT_DATASET_ID NVARCHAR(255),
    IS_PRIVATE BOOLEAN,
    PRIVATE_CREATOR NVARCHAR(255),
    SOP_INSTANCE_ID NVARCHAR(255),
    INSTANCE_NUMBER BIGINT,
    IMAGE_OCCURRENCE_ID BIGINT NOT NULL,
    ETL_CREATED_DATETIME TIMESTAMP,
    ETL_MODIFIED_DATETIME TIMESTAMP
);


CREATE TABLE DICOM_DATA_ELEMENT(
    DATA_ELEMENT_ID BIGINT NOT NULL,
    DATA_ELEMENT_TAG NVARCHAR(20) NOT NULL,
    DATA_ELEMENT_NAME NVARCHAR(255),
    DATA_ELEMENT_KEYWORD NVARCHAR(255),
    VALUE_REPRESENTATION NVARCHAR(20),
    VALUE_MULTIPLICITY NVARCHAR(20),
    IS_PRIVATE BOOLEAN,
    IS_RETIRED BOOLEAN,
    RETIRED_REMARKS NVARCHAR(255),
    ETL_CREATED_DATETIME TIMESTAMP,
    ETL_MODIFIED_DATETIME TIMESTAMP
);