--liquibase formatted sql
--changeset alp:V1.0.0.0.6__update_cohort_tables.sql

ALTER TABLE "COHORT" ALTER COLUMN "COHORT_END_DATE" drop NOT NULL;
ALTER TABLE "COHORT" ALTER COLUMN "COHORT_END_DATE" TYPE TIMESTAMP;
ALTER TABLE "COHORT" ALTER COLUMN "COHORT_START_DATE" TYPE TIMESTAMP;

ALTER TABLE "COHORT_DEFINITION" ALTER COLUMN "COHORT_INITIATION_DATE" TYPE TIMESTAMP;

ALTER TABLE "COHORT_DEFINITION"
ADD COLUMN "COHORT_MODIFICATION_DATE" TIMESTAMP NULL,
ADD COLUMN "OWNER" VARCHAR(255) NOT NULL;

ALTER TABLE "CONCEPT_SYNONYM" ALTER COLUMN "CONCEPT_SYNONYM_NAME" TYPE VARCHAR(2000);