--liquibase formatted sql
--changeset alp:V5.4.1.2.1_alter_concept_recommended_add_versioning.sql

-- CONCEPT_RECOMMENDED
CREATE COLUMN TABLE "CONCEPT_RECOMMENDED_HISTORY" AS 
(
    SELECT * FROM "CONCEPT_RECOMMENDED"
);

ALTER TABLE "CONCEPT_RECOMMENDED" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW START,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL GENERATED ALWAYS AS ROW END
);
ALTER TABLE "CONCEPT_RECOMMENDED_HISTORY" ADD (
    "SYSTEM_VALID_FROM"                 LONGDATE CS_LONGDATE NOT NULL,
    "SYSTEM_VALID_UNTIL"                LONGDATE CS_LONGDATE NOT NULL
);

ALTER TABLE "CONCEPT_RECOMMENDED" ADD PERIOD FOR SYSTEM_TIME (SYSTEM_VALID_FROM, SYSTEM_VALID_UNTIL);
ALTER TABLE "CONCEPT_RECOMMENDED" ADD SYSTEM VERSIONING HISTORY TABLE "CONCEPT_RECOMMENDED_HISTORY";
